"""
Script to build a comprehensive companies.json with 1000+ companies.
Run this once to regenerate the companies list.
"""
import json
from collections import Counter

# ============================================================
# GREENHOUSE COMPANIES
# ============================================================
greenhouse = [
    # ---- ORIGINAL (kept as-is) ----
    ("Okta", "okta"), ("Twilio", "twilio"), ("Datadog", "datadog"),
    ("Cloudflare", "cloudflare"), ("Coinbase", "coinbase"), ("HubSpot", "hubspot"),
    ("MongoDB", "mongodb"), ("Elastic", "elastic"), ("Databricks", "databricks"),
    ("Figma", "figma"), ("Zscaler", "zscaler"), ("Contentful", "contentful"),
    ("Intercom", "intercom"), ("Klaviyo", "klaviyo"), ("Gusto", "gusto"),
    ("Toast", "toast"), ("Brex", "brex"), ("Affirm", "affirm"),
    ("6sense", "6sense"), ("Braze", "braze"), ("PagerDuty", "pagerduty"),
    ("Samsara", "samsara"), ("Lattice", "lattice"), ("Asana", "asana"),
    ("Dropbox", "dropbox"), ("Reddit", "reddit"), ("Roblox", "roblox"),
    ("GitLab", "gitlab"), ("Stripe", "stripe"), ("Anthropic", "anthropic"),
    ("Scale AI", "scaleai"), ("Discord", "discord"), ("Duolingo", "duolingo"),
    ("Instacart", "instacart"), ("Lyft", "lyft"), ("Robinhood", "robinhood"),
    ("SoFi", "sofi"), ("Block", "block"), ("Airtable", "airtable"),
    ("Cockroach Labs", "cockroachlabs"), ("Grafana Labs", "grafanalabs"),
    ("Lucid Software", "lucidsoftware"), ("Vercel", "vercel"), ("Webflow", "webflow"),
    ("Carta", "carta"), ("Faire", "faire"), ("Flexport", "flexport"),
    ("GoFundMe", "gofundme"), ("Nuro", "nuro"), ("OneTrust", "onetrust"),
    ("Pendo", "pendo"), ("Remote", "remote"), ("Rubrik", "rubrik"),
    ("Sigma Computing", "sigmacomputing"), ("Smartsheet", "smartsheet"),
    ("Squarespace", "squarespace"), ("Starburst", "starburst"),
    ("Sumo Logic", "sumologic"), ("Turing", "turing"), ("Upstart", "upstart"),
    ("Verkada", "verkada"), ("Via", "via"), ("Workato", "workato"),
    ("Yext", "yext"), ("Yubico", "yubico"), ("Apollo.io", "apolloio"),
    ("Attentive", "attentive"), ("New Relic", "newrelic"),
    ("LaunchDarkly", "launchdarkly"), ("Razorpay", "razorpaysoftwareprivatelimited"),
    ("Scopely", "scopely"), ("Capco", "capco"), ("Instawork", "instawork"),
    ("Arcana Analytics", "arcanaanalytics"), ("Sigmoid", "sigmoid"),
    ("Moniepoint", "moniepoint"), ("Point72", "point72"), ("CommerceIQ", "commerceiq"),
    ("Headout", "headoutcareers"), ("Metropolis", "metropolis"), ("JazzX AI", "jazzx-ai"),
    ("Ethos", "ethos"), ("Postman", "postman"),
    # ---- DATA / ANALYTICS TOOLS ----
    ("Mixpanel", "mixpanel"), ("Amplitude", "amplitude"), ("dbt Labs", "dbtlabs"),
    ("Fivetran", "fivetran"), ("Heap", "heap"), ("ThoughtSpot", "thoughtspot"),
    ("Alteryx", "alteryx"), ("Collibra", "collibra"), ("Alation", "alation"),
    ("Atlan", "atlan"), ("Monte Carlo", "montecarlodata"), ("Airbyte", "airbyte"),
    ("Astronomer", "astronomer"), ("Prefect", "prefect"), ("Sisense", "sisense"),
    ("Informatica", "informatica"), ("Matillion", "matillion"), ("Domo", "domo"),
    ("Qlik", "qlik"), ("Microstrategy", "microstrategy"), ("Talend", "talend"),
    ("Supermetrics", "supermetrics"), ("Triple Whale", "triplewhale"),
    ("Revenuecat", "revenuecat"),
    # ---- MAJOR GLOBAL TECH ----
    ("Airbnb", "airbnb"), ("Pinterest", "pinterest"), ("Snap Inc.", "snap"),
    ("Spotify", "spotify"), ("Box", "box"), ("Zendesk", "zendesk"),
    ("Splunk", "splunk"), ("HashiCorp", "hashicorp"), ("Confluent", "confluent"),
    ("Snowflake", "snowflake"), ("Palantir", "palantir"), ("Plaid", "plaid"),
    ("Chime", "chime"), ("Marqeta", "marqeta"), ("Rippling", "rippling"),
    ("Deel", "deel"), ("ServiceTitan", "servicetitan"), ("Procore", "procore"),
    ("Veeva Systems", "veeva"), ("Shopify", "shopify"), ("DoorDash", "doordash"),
    ("Grab", "grab"), ("Gojek", "gojek"), ("SentinelOne", "sentinelone"),
    ("Gainsight", "gainsight"), ("Medallia", "medallia"), ("Qualtrics", "qualtrics"),
    ("Sprout Social", "sproutsocial"), ("Canva", "canva"), ("Miro", "miro"),
    ("FullStory", "fullstory"), ("Criteo", "criteo"), ("Taboola", "taboola"),
    ("Outbrain", "outbrain"), ("Appsflyer", "appsflyer"), ("Adjust", "adjust"),
    ("Branch.io", "branch"), ("Adobe", "adobe"), ("Retool", "retool"),
    ("OpenAI", "openai"), ("Cohere", "cohere"), ("Hugging Face", "huggingface"),
    ("Glean", "glean"), ("Perplexity AI", "perplexityai"), ("Notion", "notion"),
    ("ClickUp", "clickup"), ("Monday.com", "mondaycom"), ("ElevenLabs", "elevenlabs"),
    ("AssemblyAI", "assemblyai"), ("Deepgram", "deepgram"), ("Luma AI", "lumaai"),
    ("Writer", "writer"), ("Jasper AI", "jasper"),
    ("Eventbrite", "eventbrite"), ("SeatGeek", "seatgeek"),
    ("Hopper", "hopper"), ("Lemonade", "lemonade"),
    # ---- INDIA STARTUPS / TECH ----
    ("Freshworks", "freshworks"), ("BrowserStack", "browserstack"),
    ("Chargebee", "chargebee"), ("CleverTap", "clevertap"),
    ("Zomato", "zomato"), ("Swiggy", "swiggy"),
    ("ShareChat", "sharechat"), ("InMobi", "inmobi"), ("PhonePe", "phonepe"),
    ("Nykaa", "nykaa"), ("Urban Company", "urbancompany"), ("Darwinbox", "darwinbox"),
    ("Sprinklr", "sprinklr"), ("Zenoti", "zenoti"), ("MoEngage", "moengage"),
    ("Leadsquared", "leadsquared"), ("Innovaccer", "innovaccer"),
    ("Shiprocket", "shiprocket"), ("Delhivery", "delhivery"), ("BlackBuck", "blackbuck"),
    ("Rivigo", "rivigo"), ("HealthifyMe", "healthifyme"), ("Practo", "practo"),
    ("Acko Insurance", "acko"), ("Whatfix", "whatfix"), ("Wingify", "wingify"),
    ("WebEngage", "webengage"), ("Netcore Cloud", "netcore"), ("Exotel", "exotel"),
    ("Yellow.ai", "yellowai"), ("Haptik", "haptik"), ("Kore.ai", "koreai"),
    ("Angel One", "angelone"), ("Upstox", "upstox"), ("Smallcase", "smallcase"),
    ("ClearTax", "cleartax"), ("Lendingkart", "lendingkart"), ("OfBusiness", "ofbusiness"),
    ("Moglix", "moglix"), ("Infra.Market", "inframarket"), ("Udaan", "udaan"),
    ("Zetwerk", "zetwerk"), ("Navi Technologies", "navi"), ("Jupiter Money", "jupiter"),
    ("Cashfree Payments", "cashfree"), ("PharmEasy", "pharmeasy"),
    ("Tata 1mg", "tata1mg"), ("Apollo 247", "apollo247"),
    ("Meesho", "meesho"), ("CARS24", "cars24"), ("Ola Electric", "olaelectric"),
    ("Rapido", "rapido"), ("Ixigo", "ixigo"), ("OYO Rooms", "oyo"),
    ("BigBasket", "bigbasket"), ("Blinkit", "blinkit"), ("Zepto", "zepto"),
    ("Licious", "licious"), ("Country Delight", "countrydelight"),
    ("Mamaearth", "mamaearth"), ("boAt Lifestyle", "boatstyle"),
    ("CRED", "cred"), ("Groww", "groww"), ("Zerodha", "zerodha"),
    ("INDmoney", "indmoney"), ("Fisdom", "fisdom"), ("ETMoney", "etmoney"),
    ("Turtlemint", "turtlemint"), ("Loop Health", "loophealth"),
    ("Plum Benefits", "plumhq"), ("Onsurity", "onsurity"),
    ("Portea Medical", "portea"), ("Mfine", "mfine"),
    ("GreyOrange", "greyorange"), ("BlackBuck2", "blackbuck2"),
    ("Locus.sh", "locus"), ("Porter", "porter"),
    ("WareIQ", "wareiq"), ("Increff", "increff"), ("Unicommerce", "unicommerce"),
    ("Cashify", "cashify"), ("Lenskart", "lenskart"), ("Pepperfry", "pepperfry"),
    ("Wakefit", "wakefit"), ("Urban Ladder", "urbanladder"),
    ("Spinny", "spinny"), ("CarDekho", "cardekho"), ("Zoomcar", "zoomcar"),
    ("Ather Energy", "atherenergy"), ("Khatabook", "khatabook"),
    ("BharatPe", "bharatpe"), ("Instamojo", "instamojo"),
    ("CoverFox", "coverfox"), ("Acceldata", "acceldata"),
    ("upGrad", "upgrad"), ("Unacademy", "unacademy"), ("Vedantu", "vedantu"),
    ("Physics Wallah", "physicswallah"), ("Great Learning", "greatlearning"),
    ("Simplilearn", "simplilearn"), ("BYJU S", "byjus"),
    ("Embibe", "embibe"), ("Doubtnut", "doubtnut"),
    ("LambdaTest", "lambdatest"), ("Gupshup", "gupshup"),
    ("Kaleyra", "kaleyra"), ("Ozonetel", "ozonetel"),
    ("Setu", "setu"), ("Decentro", "decentro"), ("Juspay", "juspay"),
    ("Open Money", "openmoney"), ("Perfios", "perfios"),
    ("Capillary Technologies", "capillary"),
    ("Nium", "nium"), ("Hevo Data", "hevodata"),
    ("Signzy", "signzy"), ("Sarvam AI GH", "sarvam"),
    ("Wadhwani AI", "wadhwaniai"), ("Entropik", "entropik"),
    ("iMerit", "imerit"), ("Labelbox", "labelbox"),
    ("Weights & Biases", "wandb"), ("Together AI", "togetherai"),
    ("Fireworks AI", "fireworksai"), ("Groq", "groq"),
    ("Cerebras Systems", "cerebras"), ("SambaNova", "sambanova"),
    ("AI21 Labs", "ai21labs"), ("Stability AI", "stabilityai"),
    ("Descript", "descript"), ("Synthesia", "synthesia"),
    ("Otter.ai", "otterai"), ("Copy.ai", "copyai"),
    ("You.com", "youcom"), ("Character.AI", "characterai"),
    ("Pictor Labs", "pictor"),
    # ---- INTERNATIONAL REMOTE-FIRST COMPANIES ----
    # Remote-first tech
    ("Zapier", "zapier"), ("Buffer", "buffer"), ("Automattic", "automattic"),
    ("Help Scout", "helpscout"), ("Close", "close"), ("Customer.io", "customerio"),
    ("Doist", "doist"), ("Hotjar GH", "hotjar"), ("TestGorilla", "testgorilla"),
    ("SafetyCulture", "safetyculture"), ("Remote.com GH", "remotecom"),
    ("Oyster HR", "oysterhr"), ("Papaya Global", "papayaglobal"),
    ("Velocity Global", "velocityglobal"), ("Multiplier", "multiplier"),
    # Data / Analytics remote
    ("Mode Analytics", "modeanalytics"), ("Census", "census"),
    ("Hightouch", "hightouch"), ("RudderStack", "rudderstack"),
    ("Preset", "preset"), ("Lightdash", "lightdash"), ("Evidence", "evidence"),
    ("Cube", "cube"), ("Metabase GH", "metabase"), ("PostHog", "posthog"),
    ("Statsig GH", "statsig"), ("GrowthBook", "growthbook"),
    # FinTech remote (outside India)
    ("Wise", "wise"), ("Revolut", "revolut"), ("N26", "n26"),
    ("Monzo", "monzo"), ("OakNorth", "oaknorth"), ("Checkout.com", "checkoutcom"),
    ("Adyen", "adyen"), ("Mollie", "mollie"), ("GoCardless", "gocardless"),
    ("Tide", "tide"), ("Starling Bank", "starlingbank"),
    ("TransferGo", "transfergo"), ("Payoneer", "payoneer"),
    # AI / ML remote
    ("Runway", "runwayml"), ("Midjourney", "midjourney"),
    ("Cursor AI", "cursorai"), ("Mistral AI", "mistralai"),
    ("Inflection AI", "inflectionai"), ("Covariant", "covariant"),
    ("Shield AI", "shieldai"), ("DataRobot", "datarobot"),
    ("H2O.ai", "h2oai"), ("Dataiku", "dataiku"),
    ("Appen", "appen"), ("Telus International AI", "telusinternational"),
    # Developer tools remote
    ("Supabase GH", "supabase"), ("Railway", "railway"), ("Render GH", "render"),
    ("Fly.io", "flyio"), ("Neon", "neon"), ("Turso", "turso"),
    ("Grafbase", "grafbase"), ("Upstash", "upstash"),
    ("Sourcegraph", "sourcegraph"), ("Gitpod", "gitpod"),
    ("Codespaces", "codespaces"), ("GitPod2", "gitpod2"),
    # E-commerce / Marketplace remote
    ("Shopify GH", "shopify"), ("BigCommerce", "bigcommerce"),
    ("Etsy", "etsy"), ("Mercari", "mercari"),
    ("Poshmark", "poshmark"), ("ThredUp", "thredup"),
    # Collaboration / Productivity remote
    ("Loom", "loom"), ("Mural", "mural"),
    ("Pitch", "pitch"), ("Coda", "coda"), ("Tally", "tally"),
    ("Cal.com", "calcom"), ("Resend", "resend"),
    # Health / Wellness remote
    ("Calm GH", "calm"), ("Noom", "noom"),
    ("Hims GH", "hims"), ("Ro GH", "ro"),
    # Travel remote
    ("Skyscanner GH", "skyscanner"), ("Kiwi.com", "kiwicom"),
    ("TripActions", "tripactions"), ("Navan", "navan"),
    # ---- EXPANSION: ADDITIONAL GLOBAL TECH ----
    ("Twitch", "twitch"), ("Unity Technologies", "unity"),
    ("Epic Games", "epicgames"), ("Niantic", "niantic"),
    ("Zynga", "zynga"), ("Riot Games", "riotgames"),
    ("Waymo", "waymo"), ("Cruise", "cruise"),
    ("Aurora Innovation", "aurora"), ("Nuro GH", "nuro"),
    ("Tempus", "tempus"), ("Color Health", "color"),
    ("Devoted Health", "devotedhealth"), ("Oscar Health", "oscarhealth"),
    ("Clover Health", "cloverhealth"), ("Cerebral GH", "cerebral"),
    ("Peloton", "peloton"), ("Calm GH2", "calm"),
    ("Strava", "strava"), ("AllTrails", "alltrails"),
    ("Grammarly", "grammarly"), ("Calendly GH", "calendly"),
    ("Gong", "gong"), ("ZoomInfo", "zoominfo"),
    ("Outreach", "outreach"), ("Salesloft", "salesloft"),
    ("People.ai", "peopleai"), ("Highspot", "highspot"),
    ("Seismic", "seismic"), ("Showpad", "showpad"),
    ("Vidyard", "vidyard"), ("Loom GH", "loom"),
    ("Vimeo", "vimeo"), ("Wistia", "wistia"),
    ("Calendly GH2", "calendly2"), ("Typeform", "typeform"),
    ("SurveyMonkey GH", "surveymonkey"), ("Momentive", "momentive"),
    ("Olo", "olo"), ("Patreon", "patreon"),
    ("Substack", "substack"), ("Medium", "medium"),
    ("Ghost", "ghost"), ("Webflow GH", "webflow"),
    ("Wix", "wix"), ("Squarespace GH2", "squarespace2"),
    # ---- EXPANSION: INDIA COMPANIES ----
    ("Flipkart", "flipkart"), ("Myntra", "myntra"),
    ("FirstCry", "firstcry"), ("Ajio", "ajio"),
    ("Pine Labs", "pinelabs"), ("Eruditus", "eruditus"),
    ("Curefit", "curefit"), ("Cult.fit", "cultfit"),
    ("Rebel Foods", "rebelfoods"), ("Dunzo GH", "dunzo"),
    ("Zeta Tech", "zetatech"), ("Jar App", "jar"),
    ("Slice GH", "slice"), ("Fi Money", "fimoney"),
    ("Paytm GH", "paytm"), ("PolicyBazaar", "policybazaar"),
    ("PB Fintech", "pbfintech"), ("Dream11", "dream11"),
    ("Games24x7", "games24x7"), ("MPL", "mpl"),
    ("WinZO", "winzo"), ("Nazara Technologies", "nazara"),
    ("Rupeek", "rupeek"), ("MoneyTap", "moneytap"),
    ("Niyo", "niyo"), ("RazorpayX", "razorpayx"),
    ("Mindtickle", "mindtickle"), ("Highradius", "highradius"),
    ("Druva", "druva"), ("Icertis", "icertis"),
    ("Infra.Market GH", "inframarket"), ("OfBusiness GH", "ofbusiness"),
    ("Rivigo GH", "rivigo"), ("ElasticRun", "elasticrun"),
    ("Delhivery GH", "delhivery"), ("Shiprocket GH", "shiprocket"),
    ("Zeta Suite", "zetasuite"), ("Recko", "recko"),
    ("M2P Fintech", "m2pfintech"), ("ToneTag", "tonetag"),
    ("Mintifi", "mintifi"), ("Progcap", "progcap"),
    ("CredAvenue", "credavenue"), ("Vivriti Capital", "vivriti"),
    # ---- EXPANSION: ANALYTICS / CONSULTING ----
    ("Tiger Analytics", "tigeranalytics"), ("LatentView", "latentview"),
    ("Tredence", "tredence"), ("Absolutdata", "absolutdata"),
    ("Quantiphi", "quantiphi"), ("MathCo", "mathco"),
    ("Polestar Solutions", "polestarsolutions"), ("Cartesian Consulting", "cartesian"),
    ("TheMathCompany GH", "themathcompany"), ("Course5i", "course5i"),
    ("DecisionPoint", "decisionpoint"), ("BRIDGEi2i", "bridgei2i"),
    # ---- EXPANSION: REMOTE-FIRST ADDITIONS ----
    ("Toptal", "toptal"), ("Crossover", "crossover"),
    ("Arc.dev", "arcdev"), ("RemoteOK", "remoteok"),
    ("Kraken", "kraken"), ("Gemini Exchange", "geminiexchange"),
    ("Circle Internet", "circle"), ("Chainlink Labs", "chainlinklabs"),
    ("Protocol Labs", "protocollabs"), ("ConsenSys", "consensys"),
    ("Polygon Labs", "polygonlabs"), ("Alchemy", "alchemy"),
    ("Infura", "infura"), ("Chainalysis", "chainalysis"),
    ("Elliptic", "elliptic"), ("Nansen", "nansen"),
    ("Dune Analytics", "duneanalytics"), ("Flipside Crypto", "flipsidecrypto"),
    # ---- EXPANSION: FMCG / RETAIL / CONSUMER ----
    ("Titan Company", "titan"), ("Trent Limited", "trent"),
    ("Britannia GH", "britannia"), ("Parle Products", "parle"),
    ("ITC GH", "itcltd"), ("Godrej Consumer", "godrejconsumer"),
    ("Emami", "emami"), ("Dabur GH", "dabur"),
    ("Marico GH", "marico"), ("Crompton Greaves", "cromptongreaves"),
    ("Havells India", "havells"), ("V-Guard", "vguard"),
]

# ============================================================
# WORKDAY COMPANIES
# ============================================================
workday = [
    # (name, base_url, tenant, site_name)
    ("Kyndryl", "https://kyndryl.wd5.myworkdayjobs.com", "kyndryl", "KyndrylProfessionalCareers"),
    ("Sagility", "https://sagility.wd1.myworkdayjobs.com", "sagility", "Sagility_Careers_IND"),
    ("DXC Technology", "https://dxctechnology.wd1.myworkdayjobs.com", "dxctechnology", "DXCJobs"),
    ("Genpact", "https://genpact.wd108.myworkdayjobs.com", "genpact", "External_Careers"),
    ("Guidehouse", "https://guidehouse.wd1.myworkdayjobs.com", "guidehouse", "External"),
    ("Target", "https://target.wd5.myworkdayjobs.com", "target", "targetcareers"),
    ("Accenture", "https://accenture.wd103.myworkdayjobs.com", "accenture", "AccentureCareers"),
    ("Broadridge", "https://broadridge.wd5.myworkdayjobs.com", "broadridge", "Careers"),
    ("Amex GBT", "https://travelhrportal.wd1.myworkdayjobs.com", "travelhrportal", "Jobs"),
    ("Hitachi", "https://hitachi.wd1.myworkdayjobs.com", "hitachi", "hitachi"),
    ("Thomson Reuters", "https://thomsonreuters.wd5.myworkdayjobs.com", "thomsonreuters", "External_Career_Site"),
    # Indian IT Majors
    ("IBM", "https://ibm.wd12.myworkdayjobs.com", "ibm", "Careers"),
    ("Capgemini", "https://capgemini.wd3.myworkdayjobs.com", "capgemini", "Capgemini_Careers"),
    ("Wipro", "https://wipro.wd3.myworkdayjobs.com", "wipro", "Wipro_Careers"),
    ("Infosys", "https://infosys.wd3.myworkdayjobs.com", "infosys", "Careers"),
    ("HCL Technologies", "https://hcl.wd5.myworkdayjobs.com", "hcl", "Careers"),
    ("Tech Mahindra", "https://techmahindra.wd3.myworkdayjobs.com", "techmahindra", "Careers"),
    ("Mphasis", "https://mphasis.wd5.myworkdayjobs.com", "mphasis", "Mphasis_Careers"),
    ("L&T Technology Services", "https://ltts.wd3.myworkdayjobs.com", "ltts", "LTTS_Careers"),
    ("Persistent Systems", "https://persistent.wd5.myworkdayjobs.com", "persistent", "External_Careers"),
    ("LTIMindtree", "https://ltimindtree.wd3.myworkdayjobs.com", "ltimindtree", "LTIMindtree_Careers"),
    ("Cognizant", "https://cognizant.wd5.myworkdayjobs.com", "cognizant", "Cognizant_Careers"),
    ("EXL Service", "https://exlservice.wd5.myworkdayjobs.com", "exlservice", "Careers"),
    ("WNS Global Services", "https://wns.wd3.myworkdayjobs.com", "wns", "Careers"),
    ("Hexaware", "https://hexaware.wd5.myworkdayjobs.com", "hexaware", "Hexaware_Careers"),
    ("Zensar Technologies", "https://zensar.wd3.myworkdayjobs.com", "zensar", "Zensar_Careers"),
    ("Birlasoft", "https://birlasoft.wd5.myworkdayjobs.com", "birlasoft", "Birlasoft_Careers"),
    ("KPIT Technologies", "https://kpit.wd3.myworkdayjobs.com", "kpit", "Careers"),
    ("Cyient", "https://cyient.wd5.myworkdayjobs.com", "cyient", "Careers"),
    ("Tata Elxsi", "https://tataelxsi.wd5.myworkdayjobs.com", "tataelxsi", "Careers"),
    ("Nagarro", "https://nagarro.wd3.myworkdayjobs.com", "nagarro", "Nagarro_Careers"),
    ("Publicis Sapient", "https://publicissapient.wd3.myworkdayjobs.com", "publicissapient", "Careers"),
    ("UST Global", "https://ust.wd1.myworkdayjobs.com", "ust", "External_Careers"),
    ("NTT Data", "https://nttdata.wd3.myworkdayjobs.com", "nttdata", "External"),
    ("Happiest Minds", "https://happiestminds.wd5.myworkdayjobs.com", "happiestminds", "Careers"),
    ("Sonata Software", "https://sonata.wd5.myworkdayjobs.com", "sonata", "Careers"),
    ("NIIT Technologies", "https://niit.wd3.myworkdayjobs.com", "niit", "Careers"),
    # Consulting & Big 4
    ("McKinsey India", "https://mckinsey.wd1.myworkdayjobs.com", "mckinsey", "McKinseyandCo"),
    ("BCG India", "https://bcg.wd3.myworkdayjobs.com", "bcg", "BCGJob"),
    ("Bain & Company", "https://bain.wd1.myworkdayjobs.com", "bain", "Bain_Company_External_Career_Site"),
    ("Deloitte India", "https://deloitte.wd5.myworkdayjobs.com", "deloitte", "Deloitte_Global"),
    ("PwC India", "https://pwc.wd3.myworkdayjobs.com", "pwc", "Global"),
    ("KPMG India", "https://kpmgcareers.wd3.myworkdayjobs.com", "kpmgcareers", "KPMG_External_Careers"),
    ("EY India", "https://ey.wd5.myworkdayjobs.com", "ey", "ERX"),
    ("Grant Thornton India", "https://grantthornton.wd5.myworkdayjobs.com", "grantthornton", "GrantThornton_Careers"),
    ("RSM India", "https://rsm.wd5.myworkdayjobs.com", "rsm", "rsm_us_careers"),
    ("BDO India", "https://bdo.wd3.myworkdayjobs.com", "bdo", "BDO_Careers"),
    # Global Tech MNCs
    ("Microsoft India", "https://microsoft.wd5.myworkdayjobs.com", "microsoft", "msft-ext"),
    ("Google India", "https://google.wd3.myworkdayjobs.com", "google", "Google_External_Career_Site"),
    ("Meta India", "https://metacareers.wd5.myworkdayjobs.com", "metacareers", "CareersAtMeta"),
    ("Salesforce India", "https://salesforce.wd12.myworkdayjobs.com", "salesforce", "External_Career_Site"),
    ("Cisco India", "https://cisco.wd5.myworkdayjobs.com", "cisco", "Cisco_External_Site"),
    ("Intel India", "https://intel.wd1.myworkdayjobs.com", "intel", "External"),
    ("Qualcomm India", "https://qualcomm.wd5.myworkdayjobs.com", "qualcomm", "External"),
    ("Siemens India", "https://siemens.wd3.myworkdayjobs.com", "siemens", "External_Career_Site"),
    ("Bosch India", "https://bosch.wd3.myworkdayjobs.com", "bosch", "Bosch_External_Careers"),
    ("SAP India", "https://sap.wd3.myworkdayjobs.com", "sap", "SAP_External_BG_Prehire"),
    ("Oracle India", "https://oracle.wd1.myworkdayjobs.com", "oracle", "OracleJobs"),
    ("Honeywell India", "https://honeywell.wd5.myworkdayjobs.com", "honeywell", "Honeywell"),
    ("Schneider Electric", "https://schneiderelectric.wd3.myworkdayjobs.com", "schneiderelectric", "Careers"),
    ("Nokia India", "https://nokia.wd3.myworkdayjobs.com", "nokia", "Nokia_External_Career_Site"),
    ("Ericsson India", "https://ericsson.wd3.myworkdayjobs.com", "ericsson", "Ericsson_Careers"),
    ("Amdocs", "https://amdocs.wd5.myworkdayjobs.com", "amdocs", "Amdocs_External_Careers"),
    ("Autodesk India", "https://autodesk.wd1.myworkdayjobs.com", "autodesk", "Autodesk"),
    ("HARMAN International", "https://harman.wd1.myworkdayjobs.com", "harman", "External_Career_Site"),
    ("Motorola Solutions", "https://motorolasolutions.wd5.myworkdayjobs.com", "motorolasolutions", "Careers"),
    ("GE Digital", "https://ge.wd5.myworkdayjobs.com", "ge", "GE_External_Site"),
    ("Synopsys", "https://synopsys.wd5.myworkdayjobs.com", "synopsys", "External"),
    ("Cadence Design", "https://cadence.wd1.myworkdayjobs.com", "cadence", "External_Careers"),
    ("Ansys", "https://ansys.wd5.myworkdayjobs.com", "ansys", "External"),
    ("Dassault Systemes", "https://dassaultsystemes.wd3.myworkdayjobs.com", "dassaultsystemes", "Careers_External"),
    ("Bentley Systems", "https://bentley.wd5.myworkdayjobs.com", "bentley", "External"),
    ("Autodesk2", "https://autodesk.wd1.myworkdayjobs.com", "autodesk", "Autodesk"),
    ("PTC India", "https://ptc.wd1.myworkdayjobs.com", "ptc", "PTC_External_Career_Site"),
    ("Trimble India", "https://trimble.wd5.myworkdayjobs.com", "trimble", "TrimbleCareers"),
    ("Hexagon AB", "https://hexagon.wd3.myworkdayjobs.com", "hexagon", "Careers"),
    # BPO / Services
    ("Concentrix", "https://concentrix.wd5.myworkdayjobs.com", "concentrix", "External"),
    ("Sutherland", "https://sutherlandglobal.wd5.myworkdayjobs.com", "sutherlandglobal", "External_Careers"),
    ("Teleperformance India", "https://teleperformance.wd3.myworkdayjobs.com", "teleperformance", "External_Career_Site"),
    ("TTEC India", "https://ttec.wd1.myworkdayjobs.com", "ttec", "TTEC_External_Site"),
    ("Firstsource", "https://firstsource.wd3.myworkdayjobs.com", "firstsource", "Careers"),
    ("Conduent", "https://conduent.wd5.myworkdayjobs.com", "conduent", "Careers"),
    ("Startek", "https://startek.wd5.myworkdayjobs.com", "startek", "External_Careers"),
    ("Epsilon India", "https://epsilon.wd1.myworkdayjobs.com", "epsilon", "epsilon-external-careers"),
    ("EPAM Systems", "https://epam.wd5.myworkdayjobs.com", "epam", "EPAM"),
    ("Globant", "https://globant.wd3.myworkdayjobs.com", "globant", "Globant"),
    # Indian Conglomerates / Banks / MNCs
    ("HDFC Bank", "https://hdfcbank.wd5.myworkdayjobs.com", "hdfcbank", "HDFC_Bank_Careers"),
    ("ICICI Bank", "https://icicibank.wd3.myworkdayjobs.com", "icicibank", "External_Careers"),
    ("Axis Bank", "https://axisbank.wd3.myworkdayjobs.com", "axisbank", "External"),
    ("Kotak Mahindra Bank", "https://kotak.wd5.myworkdayjobs.com", "kotak", "External"),
    ("Bajaj Finserv", "https://bajajfinserv.wd3.myworkdayjobs.com", "bajajfinserv", "Careers"),
    ("Hindustan Unilever", "https://unilever.wd3.myworkdayjobs.com", "unilever", "Global"),
    ("Nestle India", "https://nestle.wd3.myworkdayjobs.com", "nestle", "Nestle_External"),
    ("Reliance Industries", "https://relianceindustries.wd5.myworkdayjobs.com", "relianceindustries", "RelCareers"),
    ("Jio", "https://jio.wd5.myworkdayjobs.com", "jio", "Careers"),
    ("Airtel", "https://airtel.wd3.myworkdayjobs.com", "airtel", "Airtel_Careers"),
    ("Mahindra Group", "https://mahindra.wd3.myworkdayjobs.com", "mahindra", "Careers"),
    ("Larsen & Toubro", "https://lt.wd3.myworkdayjobs.com", "lt", "Careers"),
    ("ITC Limited", "https://itc.wd3.myworkdayjobs.com", "itc", "Careers"),
    ("Asian Paints", "https://asianpaints.wd5.myworkdayjobs.com", "asianpaints", "Careers"),
    ("Aditya Birla Group", "https://adityabirla.wd3.myworkdayjobs.com", "adityabirla", "Careers"),
    ("Godrej Industries", "https://godrej.wd3.myworkdayjobs.com", "godrej", "Careers"),
    ("Tata Power", "https://tatapower.wd3.myworkdayjobs.com", "tatapower", "Careers"),
    ("P&G India", "https://pg.wd5.myworkdayjobs.com", "pg", "PG_External_Careers"),
    ("Colgate-Palmolive", "https://colgate.wd1.myworkdayjobs.com", "colgate", "ColgateGlobal"),
    ("Marico", "https://marico.wd3.myworkdayjobs.com", "marico", "Careers"),
    ("Dabur India", "https://dabur.wd3.myworkdayjobs.com", "dabur", "Careers"),
    ("Eaton India", "https://eaton.wd5.myworkdayjobs.com", "eaton", "EatonCareers2"),
    ("Emerson India", "https://emerson.wd5.myworkdayjobs.com", "emerson", "Emerson_External"),
    ("Rockwell Automation", "https://rockwellautomation.wd5.myworkdayjobs.com", "rockwellautomation", "External_Career_Website"),
    ("Baker Hughes", "https://bakerhughes.wd5.myworkdayjobs.com", "bakerhughes", "BH_Jobs"),
    ("Shell India", "https://shell.wd3.myworkdayjobs.com", "shell", "External_Career_Site"),
    ("3M India", "https://3m.wd1.myworkdayjobs.com", "3m", "3M_US"),
    ("Cummins India", "https://cummins.wd1.myworkdayjobs.com", "cummins", "External_Careers"),
    # Pharma / Life Sciences
    ("Dr. Reddys Labs", "https://drreddys.wd5.myworkdayjobs.com", "drreddys", "Careers"),
    ("Sun Pharma", "https://sunpharma.wd3.myworkdayjobs.com", "sunpharma", "Careers"),
    ("Cipla", "https://cipla.wd3.myworkdayjobs.com", "cipla", "Careers"),
    ("Aurobindo Pharma", "https://aurobindo.wd5.myworkdayjobs.com", "aurobindo", "Aurobindo_Careers"),
    ("Biocon", "https://biocon.wd5.myworkdayjobs.com", "biocon", "Careers"),
    ("Lupin Pharma", "https://lupin.wd3.myworkdayjobs.com", "lupin", "Careers"),
    ("Torrent Pharma", "https://torrent.wd3.myworkdayjobs.com", "torrent", "Careers"),
    ("Mankind Pharma", "https://mankind.wd3.myworkdayjobs.com", "mankind", "Careers"),
    ("Abbott India", "https://abbott.wd5.myworkdayjobs.com", "abbott", "abbottjobsus"),
    ("Pfizer India", "https://pfizer.wd1.myworkdayjobs.com", "pfizer", "PfizerExt"),
    ("AstraZeneca India", "https://astrazeneca.wd3.myworkdayjobs.com", "astrazeneca", "AstraZenecaApplications"),
    ("Roche India", "https://roche.wd3.myworkdayjobs.com", "roche", "roche-ext"),
    ("Novartis India", "https://novartis.wd3.myworkdayjobs.com", "novartis", "Novartis"),
    ("Johnson & Johnson", "https://jnj.wd5.myworkdayjobs.com", "jnj", "JNJ_External_Career_Site"),
    ("GlaxoSmithKline", "https://gsk.wd5.myworkdayjobs.com", "gsk", "Careers"),
    ("Pfizer India2", "https://pfizer.wd1.myworkdayjobs.com", "pfizer", "PfizerExt"),
    ("Merck India", "https://merck.wd5.myworkdayjobs.com", "merck", "MSD_Careers"),
    ("Sanofi India", "https://sanofi.wd3.myworkdayjobs.com", "sanofi", "External_Career_Site"),
    ("Bayer India", "https://bayer.wd3.myworkdayjobs.com", "bayer", "Careers"),
    ("Novo Nordisk India", "https://novonordisk.wd3.myworkdayjobs.com", "novonordisk", "Careers"),
    ("IQVIA India", "https://iqvia.wd5.myworkdayjobs.com", "iqvia", "IQVIA"),
    ("Syneos Health", "https://syneoshealth.wd5.myworkdayjobs.com", "syneoshealth", "Syneos_Health_Careers"),
    # Energy / Infrastructure
    ("ReNew Power", "https://renewpower.wd5.myworkdayjobs.com", "renewpower", "Careers"),
    ("JSW Energy", "https://jsw.wd3.myworkdayjobs.com", "jsw", "Careers"),
    ("Sembcorp India", "https://sembcorp.wd3.myworkdayjobs.com", "sembcorp", "Careers"),
    ("Sterlite Power", "https://sterlitepower.wd3.myworkdayjobs.com", "sterlitepower", "Careers"),
    # Real Estate / PropTech
    ("NoBroker", "https://nobroker.wd3.myworkdayjobs.com", "nobroker", "Careers"),
    # Global Analytics / Research
    ("Fractal Analytics", "https://fractal.wd5.myworkdayjobs.com", "fractal", "External"),
    ("Mu Sigma", "https://musigma.wd5.myworkdayjobs.com", "musigma", "External"),
    ("Dunnhumby", "https://dunnhumby.wd3.myworkdayjobs.com", "dunnhumby", "Careers"),
    ("Nielsen", "https://nielsen.wd5.myworkdayjobs.com", "nielsen", "External_Site"),
    ("IQVIA2", "https://iqvia.wd5.myworkdayjobs.com", "iqvia2", "IQVIA"),
    # ---- INTERNATIONAL REMOTE-FRIENDLY MNCs ----
    ("Spotify WD", "https://spotify.wd5.myworkdayjobs.com", "spotify", "Spotify_Careers"),
    ("Zillow WD", "https://zillow.wd5.myworkdayjobs.com", "zillow", "Zillow_Careers"),
    ("DocuSign WD", "https://docusign.wd5.myworkdayjobs.com", "docusign", "DocuSign_External"),
    ("Twilio WD", "https://twilio.wd5.myworkdayjobs.com", "twilio", "External"),
    ("Okta WD", "https://okta.wd5.myworkdayjobs.com", "okta", "Okta_Careers"),
    ("VMware WD", "https://vmware.wd1.myworkdayjobs.com", "vmware", "VMware_External"),
    ("Nutanix WD", "https://nutanix.wd1.myworkdayjobs.com", "nutanix", "External"),
    ("Pure Storage WD", "https://purestorage.wd1.myworkdayjobs.com", "purestorage", "External_Career_Site"),
    ("NetApp WD", "https://netapp.wd1.myworkdayjobs.com", "netapp", "NetApp_Careers"),
    ("Palo Alto Networks WD", "https://paloaltonetworks.wd5.myworkdayjobs.com", "paloaltonetworks", "Careers"),
    ("Fortinet WD", "https://fortinet.wd5.myworkdayjobs.com", "fortinet", "Fortinet_Careers"),
    ("CrowdStrike WD", "https://crowdstrike.wd5.myworkdayjobs.com", "crowdstrike", "External"),
    ("Zscaler WD", "https://zscaler.wd5.myworkdayjobs.com", "zscaler", "Zscaler_External"),
    ("Verint WD", "https://verint.wd5.myworkdayjobs.com", "verint", "External"),
    ("NICE Systems WD", "https://nice.wd1.myworkdayjobs.com", "nice", "NICE_Careers"),
    ("Teradata WD", "https://teradata.wd1.myworkdayjobs.com", "teradata", "External_Careers"),
    ("Informatica WD", "https://informatica.wd1.myworkdayjobs.com", "informatica", "Informatica_External"),
    ("Micro Focus WD", "https://microfocus.wd3.myworkdayjobs.com", "microfocus", "External"),
    ("Citrix WD", "https://citrix.wd1.myworkdayjobs.com", "citrix", "Citrix_Careers"),
    ("Commvault WD", "https://commvault.wd5.myworkdayjobs.com", "commvault", "External"),
    ("Pegasystems WD", "https://pegasystems.wd1.myworkdayjobs.com", "pegasystems", "Pega_Careers"),
    ("Thoughtworks WD", "https://thoughtworks.wd3.myworkdayjobs.com", "thoughtworks", "External"),
    ("Sapient WD", "https://sapient.wd3.myworkdayjobs.com", "sapient", "External"),
    ("Rackspace WD", "https://rackspace.wd1.myworkdayjobs.com", "rackspace", "Rackspace_Careers"),
    ("Elastic WD", "https://elastic.wd3.myworkdayjobs.com", "elastic", "External"),
    ("New Relic WD", "https://newrelic.wd5.myworkdayjobs.com", "newrelic", "External"),
    ("AppDynamics WD", "https://appdynamics.wd1.myworkdayjobs.com", "appdynamics", "External"),
    ("Datadog WD", "https://datadog.wd5.myworkdayjobs.com", "datadog", "Datadog_Careers"),
    ("Dynatrace WD", "https://dynatrace.wd3.myworkdayjobs.com", "dynatrace", "External_Career_Site"),
    ("Zendesk WD", "https://zendesk.wd1.myworkdayjobs.com", "zendesk", "External"),
    ("Freshworks WD", "https://freshworks.wd5.myworkdayjobs.com", "freshworks", "External"),
    ("UiPath WD", "https://uipath.wd3.myworkdayjobs.com", "uipath", "External"),
    ("Automation Anywhere WD", "https://automationanywhere.wd5.myworkdayjobs.com", "automationanywhere", "External"),
    ("Blue Prism WD", "https://blueprism.wd3.myworkdayjobs.com", "blueprism", "External"),
    ("Oliver Wyman WD", "https://oliverwyman.wd5.myworkdayjobs.com", "oliverwyman", "Careers"),
    ("ZS Associates WD", "https://zs.wd5.myworkdayjobs.com", "zs", "ZS_Careers"),
    ("Visa WD", "https://visa.wd5.myworkdayjobs.com", "visa", "Visa_External_Career_Site"),
    ("Mastercard WD", "https://mastercard.wd1.myworkdayjobs.com", "mastercard", "Careers"),
    ("PayPal WD", "https://paypal.wd1.myworkdayjobs.com", "paypal", "PayPal_Jobs"),
    ("American Express WD", "https://americanexpress.wd5.myworkdayjobs.com", "americanexpress", "Careers"),
    ("JPMorgan WD", "https://jpmc.wd5.myworkdayjobs.com", "jpmc", "External"),
    ("Goldman Sachs WD", "https://goldmansachs.wd1.myworkdayjobs.com", "goldmansachs", "External"),
    ("Morgan Stanley WD", "https://morganstanley.wd5.myworkdayjobs.com", "morganstanley", "MorganStanley_Careers"),
    ("Deutsche Bank WD", "https://deutschebank.wd3.myworkdayjobs.com", "deutschebank", "External"),
    ("UBS WD", "https://ubs.wd3.myworkdayjobs.com", "ubs", "Careers"),
    ("Credit Suisse WD", "https://creditsuisse.wd3.myworkdayjobs.com", "creditsuisse", "Careers"),
    ("Barclays WD", "https://barclays.wd3.myworkdayjobs.com", "barclays", "External_Careers"),
    ("HSBC WD", "https://hsbc.wd3.myworkdayjobs.com", "hsbc", "External"),
    ("Standard Chartered WD", "https://standardchartered.wd3.myworkdayjobs.com", "standardchartered", "External"),
    ("Citi WD", "https://citi.wd5.myworkdayjobs.com", "citi", "External"),
    ("BNY Mellon WD", "https://bnymellon.wd5.myworkdayjobs.com", "bnymellon", "Careers"),
    # ---- EXPANSION: ADDITIONAL MNCs WITH INDIA OFFICES ----
    ("Amazon India WD", "https://amazon.wd5.myworkdayjobs.com", "amazon", "External"),
    ("Apple India WD", "https://apple.wd1.myworkdayjobs.com", "apple", "Apple_Retail_External"),
    ("LinkedIn India WD", "https://linkedin.wd1.myworkdayjobs.com", "linkedin", "LinkedIn_Careers"),
    ("Uber India WD", "https://uber.wd5.myworkdayjobs.com", "uber", "uberCareers"),
    ("Netflix India WD", "https://netflix.wd5.myworkdayjobs.com", "netflix", "External"),
    ("Twitter India WD", "https://twitter.wd5.myworkdayjobs.com", "twitter", "External"),
    ("NVIDIA India WD", "https://nvidia.wd5.myworkdayjobs.com", "nvidia", "NVIDIAExternalCareerSite"),
    ("AMD India WD", "https://amd.wd1.myworkdayjobs.com", "amd", "AMD_Careers"),
    ("Texas Instruments WD", "https://ti.wd1.myworkdayjobs.com", "ti", "External"),
    ("Micron India WD", "https://micron.wd1.myworkdayjobs.com", "micron", "External_Careers"),
    ("Applied Materials WD", "https://appliedmaterials.wd1.myworkdayjobs.com", "appliedmaterials", "External_Careers"),
    ("Juniper Networks WD", "https://juniper.wd1.myworkdayjobs.com", "juniper", "External"),
    ("Hewlett Packard Enterprise WD", "https://hpe.wd5.myworkdayjobs.com", "hpe", "External"),
    ("Dell India WD", "https://dell.wd1.myworkdayjobs.com", "dell", "External"),
    ("Lenovo India WD", "https://lenovo.wd1.myworkdayjobs.com", "lenovo", "Lenovo_External"),
    ("ABB India WD", "https://abb.wd3.myworkdayjobs.com", "abb", "External"),
    ("Philips India WD", "https://philips.wd3.myworkdayjobs.com", "philips", "Careers"),
    ("Medtronic India WD", "https://medtronic.wd1.myworkdayjobs.com", "medtronic", "Medtronic_External"),
    ("Boston Scientific WD", "https://bostonscientific.wd1.myworkdayjobs.com", "bostonscientific", "Careers"),
    ("Edwards Lifesciences WD", "https://edwards.wd5.myworkdayjobs.com", "edwards", "External"),
    ("Caterpillar India WD", "https://caterpillar.wd5.myworkdayjobs.com", "caterpillar", "External"),
    ("John Deere India WD", "https://johndeere.wd1.myworkdayjobs.com", "johndeere", "External"),
    ("Volvo India WD", "https://volvo.wd3.myworkdayjobs.com", "volvo", "VolvoGroupExternal"),
    ("Mercedes-Benz India WD", "https://daimler.wd3.myworkdayjobs.com", "daimler", "External"),
    ("BMW India WD", "https://bmw.wd3.myworkdayjobs.com", "bmw", "External_Careers"),
    # ---- EXPANSION: INSURANCE / FINANCE INDIA ----
    ("Bajaj Allianz WD", "https://bajajallianz.wd3.myworkdayjobs.com", "bajajallianz", "Careers"),
    ("HDFC Life WD", "https://hdfclife.wd5.myworkdayjobs.com", "hdfclife", "External"),
    ("SBI Life WD", "https://sbilife.wd3.myworkdayjobs.com", "sbilife", "Careers"),
    ("ICICI Lombard WD", "https://icicilombard.wd3.myworkdayjobs.com", "icicilombard", "Careers"),
    ("Max Life WD", "https://maxlife.wd3.myworkdayjobs.com", "maxlife", "Careers"),
    ("Star Health WD", "https://starhealth.wd3.myworkdayjobs.com", "starhealth", "Careers"),
    ("Yes Bank WD", "https://yesbank.wd3.myworkdayjobs.com", "yesbank", "External"),
    ("RBL Bank WD", "https://rblbank.wd3.myworkdayjobs.com", "rblbank", "Careers"),
    ("Federal Bank WD", "https://federalbank.wd3.myworkdayjobs.com", "federalbank", "Careers"),
    ("IndusInd Bank WD", "https://indusind.wd3.myworkdayjobs.com", "indusind", "Careers"),
    ("Bandhan Bank WD", "https://bandhanbank.wd3.myworkdayjobs.com", "bandhanbank", "Careers"),
    # ---- EXPANSION: TELECOM / MEDIA ----
    ("Vodafone Idea WD", "https://vodafoneidea.wd3.myworkdayjobs.com", "vodafoneidea", "Careers"),
    ("Tata Communications WD", "https://tatacommunications.wd3.myworkdayjobs.com", "tatacommunications", "Careers"),
    ("Zee Entertainment WD", "https://zeeentertainment.wd3.myworkdayjobs.com", "zeeentertainment", "Careers"),
    ("Star India WD", "https://disney.wd5.myworkdayjobs.com", "disney", "disneycareersite"),
    ("Sony India WD", "https://sony.wd1.myworkdayjobs.com", "sony", "SonyGlobal"),
    # ---- EXPANSION: AUTOMOTIVE / MANUFACTURING INDIA ----
    ("Tata Motors WD", "https://tatamotors.wd3.myworkdayjobs.com", "tatamotors", "Careers"),
    ("Maruti Suzuki WD", "https://marutisuzuki.wd3.myworkdayjobs.com", "marutisuzuki", "Careers"),
    ("Hero MotoCorp WD", "https://heromotocorp.wd3.myworkdayjobs.com", "heromotocorp", "Careers"),
    ("TVS Motor WD", "https://tvs.wd3.myworkdayjobs.com", "tvs", "Careers"),
    ("Bajaj Auto WD", "https://bajajauto.wd3.myworkdayjobs.com", "bajajauto", "Careers"),
    # ---- EXPANSION: ADDITIONAL GLOBAL FINANCE ----
    ("State Street WD", "https://statestreet.wd1.myworkdayjobs.com", "statestreet", "External_Careers"),
    ("BlackRock WD", "https://blackrock.wd1.myworkdayjobs.com", "blackrock", "External"),
    ("Fidelity WD", "https://fidelity.wd5.myworkdayjobs.com", "fidelity", "External"),
    ("Charles Schwab WD", "https://schwab.wd1.myworkdayjobs.com", "schwab", "External"),
    ("Northern Trust WD", "https://northerntrust.wd5.myworkdayjobs.com", "northerntrust", "Careers"),
    ("Franklin Templeton WD", "https://franklintempleton.wd5.myworkdayjobs.com", "franklintempleton", "External_Careers"),
    ("T. Rowe Price WD", "https://troweprice.wd5.myworkdayjobs.com", "troweprice", "External_Careers"),
    ("Wells Fargo WD", "https://wellsfargo.wd5.myworkdayjobs.com", "wellsfargo", "External"),
    ("Bank of America WD", "https://bankofamerica.wd5.myworkdayjobs.com", "bankofamerica", "Careers"),
    ("Nomura India WD", "https://nomura.wd1.myworkdayjobs.com", "nomura", "External"),
    ("SocGen India WD", "https://societegenerale.wd3.myworkdayjobs.com", "societegenerale", "External"),
    ("BNP Paribas WD", "https://bnpparibas.wd3.myworkdayjobs.com", "bnpparibas", "External"),
    ("Natixis India WD", "https://natixis.wd3.myworkdayjobs.com", "natixis", "Careers"),
    # ---- EXPANSION: ADDITIONAL CONSULTING ----
    ("Accenture Strategy WD", "https://accenture.wd103.myworkdayjobs.com", "accenture", "AccentureStrategy"),
    ("Capgemini Invent WD", "https://capgemini.wd3.myworkdayjobs.com", "capgemini", "Invent_Careers"),
    ("Oliver Wyman India WD", "https://oliverwyman.wd5.myworkdayjobs.com", "oliverwyman", "External"),
    ("LEK Consulting WD", "https://lek.wd1.myworkdayjobs.com", "lek", "External"),
    ("Alvarez Marsal WD", "https://alvarezandmarsal.wd1.myworkdayjobs.com", "alvarezandmarsal", "External"),
    ("FTI Consulting WD", "https://fticonsulting.wd5.myworkdayjobs.com", "fticonsulting", "External"),
    ("Kearney WD", "https://kearney.wd3.myworkdayjobs.com", "kearney", "External"),
    ("Roland Berger WD", "https://rolandberger.wd3.myworkdayjobs.com", "rolandberger", "External"),
    ("Kantar WD", "https://kantar.wd3.myworkdayjobs.com", "kantar", "External_Careers"),
    ("NielsenIQ WD", "https://nielseniq.wd5.myworkdayjobs.com", "nielseniq", "External"),
]

# ============================================================
# LEVER COMPANIES
# ============================================================
lever = [
    # (name, company_slug)
    # Original
    ("Nium", "nium"), ("Hevo Data", "hevodata"), ("Brillio", "brillio-2"),
    ("Dun & Bradstreet", "dnb"), ("MoonPay", "moonpay"), ("Paytm", "paytm"),
    ("Genesis Global", "genesis"), ("Meesho", "meesho"), ("Drivetrain", "drivetrain"),
    # More India / Global
    ("Moengage", "moengage"), ("Leadsquared", "leadsquared"),
    ("Shadowfax Tech", "shadowfax"), ("Dunzo", "dunzo"), ("InMobi Lever", "inmobi"),
    ("Chargebee Lever", "chargebee"), ("BrowserStack Lever", "browserstack"),
    ("ThoughtSpot Lever", "thoughtspot"), ("Hasura", "hasura"), ("Vymo", "vymo"),
    ("Khatabook", "khatabook"), ("BharatPe", "bharatpe"), ("Razorpay Lever", "razorpay"),
    ("ClearTax Lever", "cleartax"), ("CRED Lever", "cred"), ("Groww Lever", "groww"),
    ("Innovaccer Lever", "innovaccer"), ("Darwinbox Lever", "darwinbox"),
    ("Yellow.ai Lever", "yellow-ai"), ("Haptik Lever", "haptik"),
    ("Zetwerk Lever", "zetwerk"), ("Moglix Lever", "moglix"), ("Udaan Lever", "udaan"),
    ("Rivigo Lever", "rivigo"), ("Porter Lever", "porter"), ("Instamojo", "instamojo"),
    ("Cashify", "cashify"), ("Lenskart", "lenskart"), ("CARS24", "cars24"),
    ("CarDekho", "cardekho"), ("Spinny", "spinny"), ("Ather Energy", "atherenergy"),
    ("Rapido", "rapido"), ("Ixigo", "ixigo"), ("MakeMyTrip", "makemytrip"),
    ("OYO Rooms", "oyo"), ("Cleartrip", "cleartrip"), ("BigBasket", "bigbasket"),
    ("Blinkit", "blinkit"), ("Zepto", "zepto"), ("Licious", "licious"),
    ("Country Delight", "country-delight"), ("Mamaearth", "mamaearth"),
    ("NoBroker", "nobroker"), ("Housing.com", "housing"), ("PropTiger", "proptiger"),
    ("Slice Finance", "slice"), ("Fibe", "fibe"), ("KreditBee", "kreditbee"),
    ("Capital Float", "capitalfloat"), ("Lendingkart Lever", "lendingkart"),
    ("Perfios", "perfios"), ("Setu", "setu"), ("Decentro", "decentro"),
    ("Juspay", "juspay"), ("Open Money", "openmoney"), ("INDmoney", "indmoney"),
    ("Fisdom", "fisdom"), ("ETMoney", "etmoney"), ("Turtlemint", "turtlemint"),
    ("Loop Health", "loophealth"), ("Plum Benefits", "plumhq"), ("Onsurity", "onsurity"),
    ("Portea Medical", "portea"), ("Docsapp", "docsapp"), ("Mfine", "mfine"),
    ("upGrad", "upgrad"), ("Unacademy", "unacademy"), ("Vedantu", "vedantu"),
    ("Simplilearn", "simplilearn"), ("Great Learning", "greatlearning"),
    ("BYJU S", "byjus"), ("Physics Wallah", "physicswallah"),
    ("LambdaTest", "lambdatest"), ("Gupshup", "gupshup"), ("Kaleyra", "kaleyra"),
    ("Exotel Lever", "exotel"), ("Ozonetel", "ozonetel"),
    ("Fynd", "fynd"), ("Sprinklr Lever", "sprinklr"),
    # Global SaaS / analytics
    ("Segment Lever", "segment"), ("Mixpanel Lever", "mixpanel"),
    ("Amplitude Lever", "amplitude"), ("Heap Lever", "heap"),
    ("FullStory Lever", "fullstory"), ("Hotjar", "hotjar"),
    ("LogRocket", "logrocket"), ("Contentsquare", "contentsquare"),
    ("UserTesting", "usertesting"), ("Birdeye", "birdeye"), ("Podium", "podium"),
    ("Sprout Social Lever", "sproutsocial"), ("Hootsuite", "hootsuite"),
    ("Later", "later"), ("Bloomreach", "bloomreach"), ("Coveo", "coveo"),
    ("Optimizely", "optimizely"), ("Emarsys", "emarsys"), ("Iterable", "iterable"),
    ("Leanplum", "leanplum"), ("Dynamic Yield", "dynamicyield"), ("Nosto", "nosto"),
    ("Acquia", "acquia"), ("Sitecore", "sitecore"), ("ServiceNow", "servicenow"),
    ("Atlassian", "atlassian"), ("Wrike", "wrike"), ("ClickUp Lever", "clickup"),
    ("Harvest", "harvest"), ("Toggl", "toggl"), ("Hubstaff", "hubstaff"),
    ("Calendly", "calendly"), ("DigitalOcean", "digitalocean"), ("Netlify", "netlify"),
    ("Harness", "harness"), ("CircleCI", "circleci"), ("Buildkite", "buildkite"),
    ("Sonatype", "sonatype"), ("Snyk", "snyk"), ("Recorded Future", "recordedfuture"),
    ("ThreatConnect", "threatconnect"), ("Armis Security", "armis"),
    ("Tanium", "tanium"), ("SolarWinds", "solarwinds"), ("Sentry", "sentry"),
    ("Honeycomb.io", "honeycomb"), ("Cribl", "cribl"), ("Coralogix", "coralogix"),
    ("Logz.io", "logzio"), ("Dynatrace", "dynatrace"),
    ("Airbyte Lever", "airbyte"), ("Fivetran Lever", "fivetran"),
    ("dbt Labs Lever", "dbtlabs"), ("Astronomer Lever", "astronomer"),
    ("Prefect Lever", "prefect"), ("Databricks Lever", "databricks"),
    ("Snowflake Lever", "snowflake"), ("MongoDB Lever", "mongodb"),
    ("CockroachDB Lever", "cockroachlabs"), ("PlanetScale", "planetscale"),
    ("Supabase", "supabase"), ("SingleStore", "singlestore"),
    ("YugabyteDB", "yugabyte"), ("TimescaleDB", "timescale"),
    ("InfluxData", "influxdata"), ("ClickHouse", "clickhouse"),
    ("Pinecone", "pinecone"), ("Weaviate", "weaviate"),
    ("Weights and Biases", "wandb"), ("LangChain", "langchain"),
    ("LlamaIndex", "llamaindex"), ("Labelbox", "labelbox"),
    ("Scale AI Lever", "scaleai"), ("iMerit", "imerit"),
    ("Roboflow", "roboflow"), ("Snorkel AI", "snorkelai"),
    ("Together AI", "togetherai"), ("Fireworks AI", "fireworksai"),
    ("Groq", "groq"), ("ElevenLabs Lever", "elevenlabs"),
    ("AssemblyAI Lever", "assemblyai"), ("Deepgram Lever", "deepgram"),
    ("Retool Lever", "retool"), ("ClickUp2", "clickup2"),
    ("Pagerduty Lever", "pagerduty"), ("New Relic Lever", "newrelic"),
    ("LaunchDarkly Lever", "launchdarkly"), ("Split.io", "split"),
    ("Statsig", "statsig"), ("Confluent Lever", "confluent"),
    ("HashiCorp Lever", "hashicorp"), ("Pulumi", "pulumi"),
    ("Temporal", "temporal"), ("Grafana Labs Lever", "grafana"),
    ("ActiveCampaign", "activecampaign"), ("Klaviyo Lever", "klaviyo"),
    ("Braze Lever", "braze"), ("OneSignal", "onesignal"),
    ("Salesforce India Lever", "salesforce"), ("Workday Lever", "workday"),
    ("Zoomcar", "zoomcar"), ("Uber India", "uber"),
    ("Snapdeal", "snapdeal"), ("Pepperfry", "pepperfry"),
    ("Wakefit", "wakefit"), ("Urban Ladder", "urban-ladder"),
    ("Airbnb India", "airbnb"), ("Yatra", "yatra"),
    ("PharmEasy Lever", "pharmeasy"), ("Apollo 247 Lever", "apollo247"),
    ("Tata 1mg Lever", "tata1mg"), ("Practo Lever", "practo"),
    ("HealthifyMe Lever", "healthifyme"),
    ("SwiggyLever", "swiggy"), ("Zomato Lever", "zomato"),
    ("Nykaa Lever", "nykaa"), ("CRED2", "cred2"),
    ("Zerodha Lever", "zerodha"), ("Upstox Lever", "upstox"),
    ("Angel One Lever", "angelone"), ("Cashfree Lever", "cashfree"),
    ("Razorpay2", "razorpay2"), ("PayU Lever", "payu"),
    ("Juspay Lever", "juspay2"), ("Navi Lever", "navi"),
    ("Jupiter Money Lever", "jupiter"), ("Slice Lever", "slice2"),
    ("BharatPe2", "bharatpe2"), ("Instamojo2", "instamojo2"),
    ("OkCredit", "okcredit"), ("INDmoney2", "indmoney2"),
    ("Smallcase Lever", "smallcase"), ("Fisdom2", "fisdom2"),
    ("Embibe", "embibe"), ("Doubtnut", "doubtnut"),
    ("Meritnation", "meritnation"), ("EduRev", "edurev"),
    ("Toppr", "toppr"), ("WhiteHat Jr", "whitehatjr"),
    ("Byju s Lever2", "byjus2"), ("unacademy2", "unacademy2"),
    ("Vedantu2", "vedantu2"), ("upGrad2", "upgrad2"),
    ("Physics Wallah2", "physicswallah2"), ("Great Learning2", "greatlearning2"),
    ("Simplilearn2", "simplilearn2"),
    # Travel & Hospitality
    ("MakeMyTrip2", "makemytrip2"), ("Goibibo", "goibibo"),
    ("FabHotels", "fabhotels"), ("Zostel", "zostel"),
    # Food
    ("Licious2", "licious2"), ("Country Delight2", "countrydelight2"),
    ("Milkbasket", "milkbasket"),
    # Mobility
    ("Yulu", "yulu"), ("Rapido2", "rapido2"), ("Chalo", "chalo"),
    ("Ather Energy2", "atherenergy2"),
    # ---- INTERNATIONAL REMOTE-FIRST (LEVER) ----
    # Remote-first companies
    ("GitLab Lever", "gitlab"), ("Sourcegraph Lever", "sourcegraph"),
    ("Mattermost", "mattermost"), ("PostHog Lever", "posthog"),
    ("Cal.com Lever", "calcom"), ("Resend Lever", "resend"),
    ("Neon Lever", "neon"), ("Turso Lever", "turso"),
    # Data platforms / Analytics remote
    ("Preset Lever", "preset"), ("Lightdash Lever", "lightdash"),
    ("Evidence Lever", "evidence"), ("GrowthBook Lever", "growthbook"),
    ("Census Lever", "census"), ("Hightouch Lever", "hightouch"),
    ("RudderStack Lever", "rudderstack"), ("Segment Lever2", "segment2"),
    ("Cube Lever", "cube"), ("Metabase Lever", "metabase"),
    # FinTech remote
    ("Wise Lever", "wise"), ("Revolut Lever", "revolut"),
    ("N26 Lever", "n26"), ("Monzo Lever", "monzo"),
    ("GoCardless Lever", "gocardless"), ("Mollie Lever", "mollie"),
    ("Payoneer Lever", "payoneer"), ("Adyen Lever", "adyen"),
    ("Checkout Lever", "checkout"), ("Stripe Lever", "stripe"),
    # Developer tools
    ("Railway Lever", "railway"), ("Render Lever", "render"),
    ("Fly.io Lever", "flyio"), ("Gitpod Lever", "gitpod"),
    ("Vercel Lever", "vercel"), ("Netlify Lever", "netlify"),
    # AI / ML remote
    ("DataRobot Lever", "datarobot"), ("H2O.ai Lever", "h2oai"),
    ("Dataiku Lever", "dataiku"), ("Appen Lever", "appen"),
    ("Runway Lever", "runwayml"), ("Mistral AI Lever", "mistralai"),
    # Remote HR / EOR platforms
    ("Oyster HR Lever", "oysterhr"), ("Papaya Global Lever", "papayaglobal"),
    ("Velocity Global Lever", "velocityglobal"),
    ("Multiplier Lever", "multiplier"), ("Deel Lever", "deel"),
    ("Remote.com Lever", "remotecom"), ("Lano Lever", "lano"),
    # Collaboration / Productivity
    ("Loom Lever", "loom"), ("Mural Lever", "mural"),
    ("Pitch Lever", "pitch"), ("Coda Lever", "coda"),
    ("Tally Lever", "tally"),
    # ---- EXPANSION: ADDITIONAL INDIA LEVER ----
    ("Pine Labs Lever", "pinelabs"), ("Eruditus Lever", "eruditus"),
    ("Rebel Foods Lever", "rebelfoods"), ("Curefit Lever", "curefit"),
    ("Dream11 Lever", "dream11"), ("Games24x7 Lever", "games24x7"),
    ("MPL Lever", "mpl"), ("WinZO Lever", "winzo"),
    ("Nazara Lever", "nazara"), ("PolicyBazaar Lever", "policybazaar"),
    ("PB Fintech Lever", "pbfintech"), ("Mindtickle Lever", "mindtickle"),
    ("Highradius Lever", "highradius"), ("Druva Lever", "druva"),
    ("Icertis Lever", "icertis"), ("Flipkart Lever", "flipkart"),
    ("Myntra Lever", "myntra"), ("FirstCry Lever", "firstcry"),
    ("Ajio Lever", "ajio"), ("Zeta Lever", "zeta"),
    ("M2P Fintech Lever", "m2pfintech"), ("Mintifi Lever", "mintifi"),
    ("Progcap Lever", "progcap"), ("CredAvenue Lever", "credavenue"),
    ("Vivriti Lever", "vivriti"), ("Recko Lever", "recko"),
    ("Tiger Analytics Lever", "tigeranalytics"),
    ("LatentView Lever", "latentview"), ("Tredence Lever", "tredence"),
    ("Course5i Lever", "course5i"), ("BRIDGEi2i Lever", "bridgei2i"),
    ("Acceldata Lever", "acceldata"), ("Hevo Data Lever2", "hevodata2"),
    ("Signzy Lever", "signzy"), ("Perfios Lever", "perfios2"),
    ("Capillary Lever", "capillary"), ("Nium Lever2", "nium2"),
    # ---- EXPANSION: ADDITIONAL GLOBAL LEVER ----
    ("Twitch Lever", "twitch"), ("Unity Lever", "unity"),
    ("Epic Games Lever", "epicgames"), ("Niantic Lever", "niantic"),
    ("Grammarly Lever", "grammarly"), ("Gong Lever", "gong"),
    ("ZoomInfo Lever", "zoominfo"), ("Outreach Lever", "outreach"),
    ("Salesloft Lever", "salesloft"), ("People.ai Lever", "peopleai"),
    ("Highspot Lever", "highspot"), ("Seismic Lever", "seismic"),
    ("Typeform Lever", "typeform"), ("Patreon Lever", "patreon"),
    ("Substack Lever", "substack"), ("Medium Lever", "medium"),
    ("Vimeo Lever", "vimeo"), ("Strava Lever", "strava"),
    ("AllTrails Lever", "alltrails"), ("Peloton Lever", "peloton"),
    ("Kraken Lever", "kraken"), ("Gemini Lever", "gemini"),
    ("Circle Lever", "circle"), ("Chainlink Lever", "chainlink"),
    ("ConsenSys Lever", "consensys"), ("Polygon Lever", "polygon"),
    ("Alchemy Lever", "alchemy"), ("Chainalysis Lever", "chainalysis"),
    ("Nansen Lever", "nansen"), ("Dune Lever", "dune"),
    ("Toptal Lever", "toptal"), ("Crossover Lever", "crossover"),
]

# ============================================================
# ASHBY COMPANIES
# ============================================================
ashby = [
    # (name, board_name)
    ("Maneuver Marketing", "maneuver-marketing"),
    ("SurveyMonkey", "surveymonkey"),
    ("Juniper Square", "junipersquare"),
    ("Riveron", "riveron"),
    ("Sarvam AI", "sarvam"),
    ("UptimeAI", "uptimeai"),
    ("Altimate AI", "altimate"),
    ("Wisdom AI", "Wisdom-AI"),
    ("Aspora", "aspora"),
    ("G2", "g2"),
    ("Replit", "replit"),
    ("Superhuman", "superhuman"),
    ("Vanta", "vanta"),
    ("Drata", "drata"),
    ("Secureframe", "secureframe"),
    ("Sprinto", "sprinto"),
    ("Wiz", "wiz"),
    ("Orca Security", "orca"),
    ("Lacework", "lacework"),
    ("Aqua Security", "aquasecurity"),
    ("Sysdig", "sysdig"),
    ("Crowdstrike", "crowdstrike"),
    ("Darktrace", "darktrace"),
    ("Arctic Wolf", "arcticwolf"),
    ("Expel", "expel"),
    ("Abnormal Security", "abnormalsecurity"),
    ("HackerOne", "hackerone"),
    ("Bugcrowd", "bugcrowd"),
    ("Snyk Ashby", "snyk"),
    ("Cato Networks", "catonetworks"),
    ("Netskope", "netskope"),
    ("Jamf", "jamf"),
    ("Tines", "tines"),
    ("Swimlane", "swimlane"),
    ("JupiterOne", "jupiterone"),
    ("Harness Ashby", "harness"),
    ("Databand", "databand"),
    ("Bigeye", "bigeye"),
    ("Datafold", "datafold"),
    ("Ataccama", "ataccama"),
    ("Precisely", "precisely"),
    ("Semarchy", "semarchy"),
    ("Tamr", "tamr"),
    ("Orchestra", "orchestra"),
    ("Sifflet", "sifflet"),
    ("Saama Technologies", "saama"),
    ("Certara", "certara"),
    ("Komodo Health", "komodohealth"),
    ("Hinge Health", "hingehealth"),
    ("Sword Health", "swordhealth"),
    ("Spring Health", "springhealth"),
    ("Lyra Health", "lyrahealth"),
    ("Modern Health", "modernhealth"),
    ("Headspace", "headspace"),
    ("Natera", "natera"),
    ("Guardant Health", "guardanthealth"),
    ("10x Genomics", "10xgenomics"),
    ("Ginkgo Bioworks", "ginkgobioworks"),
    ("Recursion Pharmaceuticals", "recursion"),
    ("Beam Therapeutics", "beamtherapeutics"),
    ("VictoriaMetrics", "victoriametrics"),
    ("InfluxData Ashby", "influxdata"),
    ("Grafana Labs Ashby", "grafana"),
    ("Sentry Ashby", "sentry"),
    ("Rollbar", "rollbar"),
    ("Bugsnag", "bugsnag"),
    ("OpsLevel", "opslevel"),
    ("Kong Inc", "konginc"),
    ("Solo.io", "soloio"),
    ("Cortex", "cortex"),
    ("Port", "getport"),
    ("Mend", "mend"),
    ("Endor Labs", "endorlabs"),
    ("Cycode", "cycode"),
    ("Retool Ashby", "retool"),
    ("Budibase", "budibase"),
    ("Tooljet", "tooljet"),
    ("DronaHQ", "dronahq"),
    ("Cube Dev", "cubedev"),
    ("Metabase", "metabase"),
    ("Observable", "observable"),
    ("Hex Technologies", "hex"),
    ("Deepnote", "deepnote"),
    ("Comet ML", "cometml"),
    ("ClearML", "clearml"),
    ("Neptune AI", "neptuneai"),
    ("Fiddler AI", "fiddlerai"),
    ("Arize AI", "arizeai"),
    ("WhyLabs", "whylabs"),
    ("Arthur AI", "arthurai"),
    ("Truera", "truera"),
    ("Aporia", "aporia"),
    ("Modal", "modal"),
    ("Replicate", "replicate"),
    ("Lightning AI", "lightningai"),
    ("Baseten", "baseten"),
    ("Together AI Ashby", "togetherai"),
    ("Groq Ashby", "groq"),
    ("Cerebras Systems", "cerebras"),
    ("SambaNova Systems", "sambanova"),
    ("Graphcore", "graphcore"),
    ("Tenstorrent", "tenstorrent"),
    ("Hailo", "hailo"),
    ("Anecdotes", "anecdotes"),
    ("Thoropass", "thoropass"),
    ("SafeBase", "safebase"),
    ("UpGuard", "upguard"),
    ("SecurityScorecard", "securityscorecard"),
    ("BitSight", "bitsight"),
    ("Dragos", "dragos"),
    ("Claroty", "claroty"),
    ("Armis Ashby", "armis"),
    ("Nozomi Networks", "nozominetworks"),
    ("Illumio", "illumio"),
    ("Palo Alto Networks Ashby", "paloaltonetworks"),
    ("Proofpoint", "proofpoint"),
    ("Mimecast", "mimecast"),
    ("Tessian", "tessian"),
    ("Cofense", "cofense"),
    ("Fortra", "fortra"),
    ("Trustwave", "trustwave"),
    ("Secureworks", "secureworks"),
    ("eSentire", "esentire"),
    ("Versa Networks", "versanetworks"),
    ("Aryaka Networks", "aryaka"),
    ("Lookout", "lookout"),
    ("Kandji", "kandji"),
    ("Fleet DM", "fleetdm"),
    ("Torq", "torq"),
    ("Cribl Ashby", "cribl"),
    ("Chronosphere", "chronosphere"),
    ("Coralogix Ashby", "coralogix"),
    ("Logz.io Ashby", "logzio"),
    ("Mezmo", "mezmo"),
    ("Airbrake", "airbrake"),
    ("Instana", "instana"),
    ("Sonatype Ashby", "sonatype"),
    ("Checkmarx", "checkmarx"),
    ("Veracode", "veracode"),
    ("Contrast Security", "contrastsecurity"),
    ("Invicti", "invicti"),
    ("Detectify", "detectify"),
    ("Cobalt", "cobalt"),
    ("Synack", "synack"),
    ("Intigriti", "intigriti"),
    ("Debricked", "debricked"),
    ("Phylum", "phylum"),
    ("Socket Security", "socketdev"),
    ("Ox Security", "oxsecurity"),
    ("Legit Security", "legitsecurity"),
    ("Apiiro", "apiiro"),
    ("Anchore", "anchore"),
    ("Cyscale", "cyscale"),
    ("Lightspin", "lightspin"),
    ("Sonrai Security", "sonraisecurity"),
    ("Ermetic", "ermetic"),
    ("Bridgecrew", "bridgecrew"),
    ("Tigera", "tigera"),
    ("Kong Inc2", "konginc2"),
    ("Ambassador Labs", "ambassadorlabs"),
    ("Kubecost", "kubecost"),
    ("Apptio", "apptio"),
    ("CloudHealth", "cloudhealth"),
    ("Turbot", "turbot"),
    ("Steampipe", "steampipe"),
    ("Cloudquery", "cloudquery"),
    ("QuestDB Ashby", "questdb"),
    ("TimescaleDB Ashby", "timescaledb"),
    ("Hims & Hers", "hims"),
    ("Ro", "ro"),
    ("Cerebral", "cerebral"),
    ("Talkspace", "talkspace"),
    ("BetterHelp", "betterhelp"),
    ("Calm", "calm"),
    ("NOCD", "nocd"),
    ("Viaduct.ai", "viaduct"),
    ("Foundation Medicine", "foundationmedicine"),
    ("Grail", "grail"),
    ("Illumina", "illumina"),
    ("PacBio", "pacbio"),
    ("Seer Bio", "seerbio"),
    ("Element Biosciences", "elementbiosciences"),
    ("Mammoth Biosciences", "mammothbiosciences"),
    ("Unlearn AI", "unlearnai"),
    ("Komodo2", "komodo"),
    ("Apixio", "apixio"),
    ("Aledade", "aledade"),
    ("Natera2", "natera2"),
    ("ElevenLabs Ashby", "elevenlabs"),
    ("Perplexity Ashby", "perplexity"),
    ("Cohere Ashby", "cohere"),
    ("Luma AI Ashby", "lumaai"),
    ("AI21 Ashby", "ai21"),
    ("Stability AI Ashby", "stabilityai"),
    ("Jasper Ashby", "jasper"),
    ("Character AI Ashby", "characterai"),
    ("Adept AI", "adeptai"),
    ("Glean Ashby", "glean"),
    ("Notion Ashby", "notion"),
    ("Linear", "linear"),
    ("Coda Ashby", "coda"),
    ("Miro Ashby", "miro"),
    ("Whimsical", "whimsical"),
    ("Framer", "framer"),
    ("Canva Ashby", "canva"),
    ("InVision", "invision"),
    ("Zeplin", "zeplin"),
    ("Maze", "maze"),
    ("Dovetail", "dovetailapp"),
    ("Sprig", "sprig"),
    ("Lyssna", "lyssna"),
    ("UserZoom", "userzoom"),
    ("Birdeye Ashby", "birdeye"),
    ("Podium Ashby", "podium"),
    ("Medalllia Ashby", "medallia"),
    ("Qualtrics Ashby", "qualtrics"),
    ("G2 Crowd", "g2crowd"),
    ("TrustRadius", "trustradius"),
    ("Gartner Peer Insights", "gartner"),
    ("SoftwareReviews", "softwarereviews"),
    ("Cuspera", "cuspera"),
    ("GetApp", "getapp"),
    ("Capterra", "capterra"),
    ("Databand2", "databand2"),
    ("Monte Carlo Ashby", "montecarlodata"),
    ("Atlan Ashby", "atlan"),
    ("Alation Ashby", "alation"),
    ("Collibra Ashby", "collibra"),
    ("Alteryx Ashby", "alteryx"),
    ("ThoughtSpot Ashby", "thoughtspot"),
    ("Sisense Ashby", "sisense"),
    ("Domo Ashby", "domo"),
    ("Qlik Ashby", "qlik"),
    ("Informatica Ashby", "informatica"),
    ("Talend Ashby", "talend"),
    ("Matillion Ashby", "matillion"),
    ("Starburst Ashby", "starburst"),
    ("Airbyte Ashby", "airbyte"),
    ("Fivetran Ashby", "fivetran"),
    ("dbt Labs Ashby", "dbtlabs"),
    ("Astronomer Ashby", "astronomer"),
    ("Dagster", "dagster"),
    ("Prefect Ashby", "prefect"),
    ("Temporal Ashby", "temporal"),
    ("Pulumi Ashby", "pulumi"),
    ("HashiCorp Ashby", "hashicorp"),
    ("Confluent Ashby", "confluent"),
    ("MongoDB Ashby", "mongodb"),
    ("Snowflake Ashby", "snowflake"),
    ("Databricks Ashby", "databricks"),
    ("CockroachDB Ashby", "cockroachlabs"),
    ("Pinecone Ashby", "pinecone"),
    ("Weaviate Ashby", "weaviate"),
    ("Qdrant Ashby", "qdrant"),
    ("SingleStore Ashby", "singlestore"),
    ("YugabyteDB Ashby", "yugabyte"),
    ("ClickHouse Ashby", "clickhouse"),
    # ---- INTERNATIONAL REMOTE-FIRST (ASHBY) ----
    # AI / Data remote
    ("Dataiku Ashby", "dataiku"),
    ("Anyscale", "anyscale"),
    ("Comet ML Ashby2", "cometml2"),
    ("Neptune AI Ashby2", "neptuneai2"),
    ("Weights Biases Ashby", "wandb"),
    ("Fiddler AI Ashby2", "fiddlerai2"),
    ("Arize AI Ashby2", "arizeai2"),
    ("WhyLabs Ashby2", "whylabs2"),
    ("Modal Ashby2", "modal2"),
    ("Replicate Ashby2", "replicate2"),
    # Remote SaaS
    ("Linear Ashby2", "linear2"),
    ("Loom Ashby", "loom"),
    ("PostHog Ashby", "posthog"),
    ("Cal.com Ashby", "calcom"),
    ("Resend Ashby", "resend"),
    ("Neon Ashby", "neon"),
    ("Turso Ashby", "turso"),
    ("Railway Ashby", "railway"),
    ("Render Ashby", "render"),
    ("Fly.io Ashby", "flyio"),
    # Remote analytics
    ("Preset Ashby", "preset"),
    ("Lightdash Ashby", "lightdash"),
    ("Evidence Ashby", "evidence"),
    ("GrowthBook Ashby", "growthbook"),
    ("Census Ashby", "census"),
    ("Hightouch Ashby", "hightouch"),
    ("RudderStack Ashby", "rudderstack"),
    # Remote FinTech
    ("Wise Ashby", "wise"),
    ("Revolut Ashby", "revolut"),
    ("GoCardless Ashby", "gocardless"),
    ("Mollie Ashby", "mollie"),
    ("Checkout Ashby", "checkout"),
    # ---- EXPANSION: ADDITIONAL ASHBY ----
    ("Altruist", "altruist"), ("Plaid Ashby", "plaid"),
    ("Rippling Ashby", "rippling"), ("Deel Ashby", "deel"),
    ("Gusto Ashby", "gusto"), ("Faire Ashby", "faire"),
    ("Brex Ashby", "brex"), ("Ramp Ashby", "ramp"),
    ("Navan Ashby", "navan"), ("Canva Ashby2", "canva2"),
    ("Figma Ashby", "figma"), ("Miro Ashby2", "miro2"),
    ("Notion Ashby2", "notion2"), ("Airtable Ashby", "airtable"),
    ("Postman Ashby", "postman"), ("Vercel Ashby", "vercel"),
    ("Netlify Ashby", "netlify"), ("Supabase Ashby", "supabase"),
    ("Render Ashby2", "render2"), ("Railway Ashby2", "railway2"),
]

# ============================================================
# SMARTRECRUITERS COMPANIES
# ============================================================
smartrecruiters = [
    # (name, company_identifier)
    ("Capgemini SmartRec", "Capgemini"),
    ("Wipro SmartRec", "WIPRO"),
    ("HCL SmartRec", "HCLTechnologies"),
    ("Infosys SmartRec", "Infosys"),
    ("Tech Mahindra SmartRec", "TechMahindra"),
    ("Hexaware SmartRec", "Hexaware"),
    ("Mphasis SmartRec", "Mphasis"),
    ("Cognizant SmartRec", "Cognizant"),
    ("EXL Service SmartRec", "EXLService"),
    ("WNS SmartRec", "WNS"),
    ("Teleperformance SmartRec", "Teleperformance"),
    ("Concentrix SmartRec", "Concentrix"),
    ("Conduent SmartRec", "Conduent"),
    ("Sutherland SmartRec", "Sutherland"),
    ("TTEC SmartRec", "TTEC"),
    ("Firstsource SmartRec", "Firstsource"),
    ("Startek SmartRec", "Startek"),
    ("Mu Sigma SmartRec", "MuSigma"),
    ("Tiger Analytics SmartRec", "TigerAnalytics"),
    ("LatentView SmartRec", "LatentView"),
    ("Fractal Analytics SmartRec", "FractalAnalytics"),
    ("Quantiphi SmartRec", "Quantiphi"),
    ("MathCo SmartRec", "MathCo"),
    ("Data Axle SmartRec", "DataAxle"),
    ("Sigmoid SmartRec", "Sigmoid"),
    ("Polestar Solutions SmartRec", "PolestarSolutions"),
    ("TheMathCompany SmartRec", "TheMathCompany"),
    ("Dunnhumby SmartRec", "dunnhumby"),
    ("NielsenIQ SmartRec", "NielsenIQ"),
    ("Kantar SmartRec", "Kantar"),
    ("Ipsos SmartRec", "Ipsos"),
    ("YouGov SmartRec", "YouGov"),
    ("GfK SmartRec", "GfK"),
    ("KPMG SmartRec", "KPMG"),
    ("EY SmartRec", "EY"),
    ("PwC SmartRec", "PwC"),
    ("Deloitte SmartRec", "Deloitte"),
    ("Accenture SmartRec", "Accenture"),
    ("IBM SmartRec", "IBM"),
    ("DXC SmartRec", "DXCTechnology"),
    ("Genpact SmartRec", "Genpact"),
    ("Publicis Sapient SmartRec", "PublicisSapient"),
    ("Atos SmartRec", "Atos"),
    ("CGI Group SmartRec", "CGI"),
    ("Unisys SmartRec", "Unisys"),
    ("Fujitsu India SmartRec", "Fujitsu"),
    ("NTT Data SmartRec", "NTTData"),
    ("Luxoft SmartRec", "Luxoft"),
    ("EPAM Systems SmartRec", "EPAMSystems"),
    ("Globant SmartRec", "Globant"),
    ("Endava SmartRec", "Endava"),
    ("Grid Dynamics SmartRec", "GridDynamics"),
    ("DataArt SmartRec", "DataArt"),
    ("Happiest Minds SmartRec", "HappiestMinds"),
    ("Tata Elxsi SmartRec", "TataElxsi"),
    ("Nagarro SmartRec", "Nagarro"),
    ("Zensar SmartRec", "ZensarTechnologies"),
    ("Birlasoft SmartRec", "Birlasoft"),
    ("KPIT SmartRec", "KPIT"),
    ("Cyient SmartRec", "Cyient"),
    ("Salesforce SmartRec", "Salesforce"),
    ("ServiceNow SmartRec", "ServiceNow"),
    ("SAP SmartRec", "SAP"),
    ("Oracle SmartRec", "Oracle"),
    ("Microsoft SmartRec", "Microsoft"),
    ("Amazon SmartRec", "Amazon"),
    ("Atlassian SmartRec", "Atlassian"),
    ("Zendesk SmartRec", "Zendesk"),
    ("HubSpot SmartRec", "HubSpot"),
    ("Tableau SmartRec", "Tableau"),
    ("Qlik SmartRec", "Qlik"),
    ("MicroStrategy SmartRec", "MicroStrategy"),
    ("Domo SmartRec", "Domo"),
    ("SAS Institute SmartRec", "SASInstitute"),
    ("Anaconda SmartRec", "Anaconda"),
    ("JetBrains SmartRec", "JetBrains"),
    ("GitHub SmartRec", "GitHub"),
    ("GitLab SmartRec", "GitLab"),
    ("DigitalOcean SmartRec", "DigitalOcean"),
    ("Fastly SmartRec", "Fastly"),
    ("Akamai SmartRec", "Akamai"),
    ("Cloudflare SmartRec", "Cloudflare"),
    ("Fortinet SmartRec", "Fortinet"),
    ("Palo Alto Networks SmartRec", "PaloAltoNetworks"),
    ("Check Point SmartRec", "CheckPoint"),
    ("Sophos SmartRec", "Sophos"),
    ("Trend Micro SmartRec", "TrendMicro"),
    ("CrowdStrike SmartRec", "CrowdStrike"),
    ("Mandiant SmartRec", "Mandiant"),
    ("Rapid7 SmartRec", "Rapid7"),
    ("Tenable SmartRec", "Tenable"),
    ("Qualys SmartRec", "Qualys"),
    ("Tanium SmartRec", "Tanium"),
    ("Ivanti SmartRec", "Ivanti"),
    ("ManageEngine SmartRec", "ManageEngine"),
    ("SolarWinds SmartRec", "SolarWinds"),
    ("Recorded Future SmartRec", "RecordedFuture"),
    ("Anomali SmartRec", "Anomali"),
    ("Secureworks SmartRec", "Secureworks"),
    ("Expedia SmartRec", "Expedia"),
    ("Booking Holdings SmartRec", "Booking"),
    ("Agoda SmartRec", "Agoda"),
    ("TripAdvisor SmartRec", "TripAdvisor"),
    ("Skyscanner SmartRec", "Skyscanner"),
    ("IndiGo SmartRec", "IndiGo"),
    ("Vistara SmartRec", "Vistara"),
    ("SpiceJet SmartRec", "SpiceJet"),
    ("Akasa Air SmartRec", "AkasaAir"),
    ("ReNew Power SmartRec", "ReNewPower"),
    ("Adani Group SmartRec", "Adani"),
    ("Tata Power SmartRec", "TataPower"),
    ("JSW Energy SmartRec", "JSWEnergy"),
    ("NoBroker SmartRec", "NoBroker"),
    ("Zillow SmartRec", "Zillow"),
    ("Redfin SmartRec", "Redfin"),
    ("Compass SmartRec", "Compass"),
    ("Opendoor SmartRec", "Opendoor"),
    ("Amadeus IT SmartRec", "Amadeus"),
    ("Sabre Corporation SmartRec", "Sabre"),
    ("IBS Software SmartRec", "IBSSoftware"),
    ("Posit SmartRec", "Posit"),
    ("Zoho SmartRec", "Zoho"),
    ("Freshworks SmartRec", "Freshworks"),
    ("BrowserStack SmartRec", "BrowserStack"),
    ("MoEngage SmartRec", "MoEngage"),
    ("WebEngage SmartRec", "WebEngage"),
    ("CleverTap SmartRec", "CleverTap"),
    ("Netcore SmartRec", "NetcoreCloud"),
    ("Darwinbox SmartRec", "Darwinbox"),
    ("Keka HR SmartRec", "KekaHR"),
    ("GreytHR SmartRec", "GreytHR"),
    ("Whatfix SmartRec", "Whatfix"),
    ("LambdaTest SmartRec", "LambdaTest"),
    ("Gupshup SmartRec", "Gupshup"),
    ("Kaleyra SmartRec", "Kaleyra"),
    ("Exotel SmartRec", "Exotel"),
    ("Yellow.ai SmartRec", "YellowAI"),
    ("Haptik SmartRec", "Haptik"),
    ("Kore.ai SmartRec", "KoreAI"),
    ("Shiprocket SmartRec", "Shiprocket"),
    ("Delhivery SmartRec", "Delhivery"),
    ("Ecom Express SmartRec", "EcomExpress"),
    ("XpressBees SmartRec", "XpressBees"),
    ("Shadowfax SmartRec", "Shadowfax"),
    ("BlackBuck SmartRec", "BlackBuck"),
    ("ElasticRun SmartRec", "ElasticRun"),
    ("Increff SmartRec", "Increff"),
    ("Unicommerce SmartRec", "Unicommerce"),
    ("Nykaa SmartRec", "Nykaa"),
    ("Mamaearth SmartRec", "Mamaearth"),
    ("CARS24 SmartRec", "CARS24"),
    ("CarDekho SmartRec", "CarDekho"),
    ("Spinny SmartRec", "Spinny"),
    ("Ather Energy SmartRec", "AtherEnergy"),
    ("Ola Electric SmartRec", "OlaElectric"),
    ("Rapido SmartRec", "Rapido"),
    ("Ixigo SmartRec", "Ixigo"),
    ("OYO SmartRec", "OYO"),
    ("MakeMyTrip SmartRec", "MakeMyTrip"),
    ("BigBasket SmartRec", "BigBasket"),
    ("Swiggy SmartRec", "Swiggy"),
    ("Zomato SmartRec", "Zomato"),
    ("Blinkit SmartRec", "Blinkit"),
    ("Zepto SmartRec", "Zepto"),
    ("PharmEasy SmartRec", "PharmEasy"),
    ("Tata 1mg SmartRec", "Tata1mg"),
    ("Apollo 247 SmartRec", "Apollo247"),
    ("Practo SmartRec", "Practo"),
    ("HealthifyMe SmartRec", "HealthifyMe"),
    ("Navi SmartRec", "Navi"),
    ("Jupiter SmartRec", "JupiterMoney"),
    ("Slice SmartRec", "Slice"),
    ("Fibe SmartRec", "Fibe"),
    ("KreditBee SmartRec", "KreditBee"),
    ("BharatPe SmartRec", "BharatPe"),
    ("Razorpay SmartRec", "Razorpay"),
    ("PhonePe SmartRec", "PhonePe"),
    ("Cashfree SmartRec", "Cashfree"),
    ("Angel One SmartRec", "AngelOne"),
    ("Upstox SmartRec", "Upstox"),
    ("Groww SmartRec", "Groww"),
    ("Smallcase SmartRec", "Smallcase"),
    ("INDmoney SmartRec", "INDmoney"),
    ("ClearTax SmartRec", "ClearTax"),
    ("Innovaccer SmartRec", "Innovaccer"),
    ("upGrad SmartRec", "upGrad"),
    ("Physics Wallah SmartRec", "PhysicsWallah"),
    ("Great Learning SmartRec", "GreatLearning"),
    ("Simplilearn SmartRec", "Simplilearn"),
    ("Unacademy SmartRec", "Unacademy"),
    ("BYJU S SmartRec", "BYJUS"),
    ("Meesho SmartRec", "Meesho"),
    ("Lenskart SmartRec", "Lenskart"),
    ("Urban Company SmartRec", "UrbanCompany"),
    ("Cashify SmartRec", "Cashify"),
    ("Pepperfry SmartRec", "Pepperfry"),
    ("Wakefit SmartRec", "Wakefit"),
    ("Urban Ladder SmartRec", "UrbanLadder"),
    ("Moglix SmartRec", "Moglix"),
    ("OfBusiness SmartRec", "OfBusiness"),
    ("Zetwerk SmartRec", "Zetwerk"),
    ("Udaan SmartRec", "Udaan"),
    ("Locus.sh SmartRec", "Locus"),
    ("Porter SmartRec", "Porter"),
    ("WareIQ SmartRec", "WareIQ"),
    ("Sarvam AI SmartRec", "SarvamAI"),
    ("Wadhwani AI SmartRec", "WadhwaniAI"),
    ("Sigmoid SmartRec2", "SigmoidAnalytics"),
    ("Absolutdata SmartRec", "Absolutdata"),
    ("GreyOrange SmartRec", "GreyOrange"),
    ("CRED SmartRec", "CRED"),
    ("Khatabook SmartRec", "Khatabook"),
    ("OkCredit SmartRec", "OkCredit"),
    ("Vymo SmartRec", "Vymo"),
    ("Chargebee SmartRec", "Chargebee"),
    ("Zenoti SmartRec", "Zenoti"),
    ("Sprinklr SmartRec", "Sprinklr"),
    ("Capillary SmartRec", "CapillaryTech"),
    ("Leadsquared SmartRec", "LeadSquared"),
    ("Hevo Data SmartRec", "HevoData"),
    ("Postman SmartRec", "Postman"),
    ("Hasura SmartRec", "Hasura"),
    ("Atlan SmartRec", "Atlan"),
    ("Collibra SmartRec", "Collibra"),
    ("Alation SmartRec", "Alation"),
    ("Fivetran SmartRec", "Fivetran"),
    ("Airbyte SmartRec", "Airbyte"),
    ("dbt Labs SmartRec", "dbtLabs"),
    ("Databricks SmartRec", "Databricks"),
    ("Snowflake SmartRec", "Snowflake"),
    ("MongoDB SmartRec", "MongoDB"),
    ("Confluent SmartRec", "Confluent"),
    ("Elastic SmartRec", "Elastic"),
    ("HashiCorp SmartRec", "HashiCorp"),
    ("Splunk SmartRec", "Splunk"),
    ("Dynatrace SmartRec", "Dynatrace"),
    ("Alteryx SmartRec", "Alteryx"),
    ("Informatica SmartRec", "Informatica"),
    ("Talend SmartRec", "Talend"),
    ("Matillion SmartRec", "Matillion"),
    ("ThoughtSpot SmartRec", "ThoughtSpot"),
    ("Sigma Computing SmartRec", "SigmaComputing"),
    ("Mixpanel SmartRec", "Mixpanel"),
    ("Amplitude SmartRec", "Amplitude"),
    ("Heap SmartRec", "Heap"),
    ("FullStory SmartRec", "FullStory"),
    ("Gainsight SmartRec", "Gainsight"),
    ("Medallia SmartRec", "Medallia"),
    ("Qualtrics SmartRec", "Qualtrics"),
    ("Sprout Social SmartRec", "SproutSocial"),
    ("Hootsuite SmartRec", "Hootsuite"),
    ("Optimizely SmartRec", "Optimizely"),
    ("Criteo SmartRec", "Criteo"),
    ("Taboola SmartRec", "Taboola"),
    ("Appsflyer SmartRec", "Appsflyer"),
    ("Adjust SmartRec", "Adjust"),
    ("Branch SmartRec", "Branch"),
    ("Liftoff SmartRec", "Liftoff"),
    ("IronSource SmartRec", "IronSource"),
    ("Canva SmartRec", "Canva"),
    ("Adobe SmartRec", "Adobe"),
    ("Miro SmartRec", "Miro"),
    ("Shopify SmartRec", "Shopify"),
    ("Veeva SmartRec", "VeevaSystems"),
    ("Procore SmartRec", "Procore"),
    ("ServiceTitan SmartRec", "ServiceTitan"),
    ("Rippling SmartRec", "Rippling"),
    ("Deel SmartRec", "Deel"),
    ("Remote SmartRec", "Remote"),
    ("Gusto SmartRec", "Gusto"),
    ("Lattice SmartRec", "Lattice"),
    ("Workato SmartRec", "Workato"),
    ("Boomi SmartRec", "Boomi"),
    ("MuleSoft SmartRec", "MuleSoft"),
    ("Zapier SmartRec", "Zapier"),
    ("Jitterbit SmartRec", "Jitterbit"),
    ("SnapLogic SmartRec", "SnapLogic"),
    ("TIBCO SmartRec", "TIBCO"),
    ("Software AG SmartRec", "SoftwareAG"),
    ("ManageEngine SmartRec2", "ManageEngine2"),
    ("Freshservice SmartRec", "Freshservice"),
    ("Monday.com SmartRec", "MondayCom"),
    ("ClickUp SmartRec", "ClickUp"),
    ("Notion SmartRec", "Notion"),
    ("Airtable SmartRec", "Airtable"),
    ("SmartSheet SmartRec", "Smartsheet"),
    ("Wrike SmartRec", "Wrike"),
    ("Teamwork SmartRec", "Teamwork"),
    ("Asana SmartRec", "Asana"),
    ("Calendly SmartRec", "Calendly"),
    ("Hubstaff SmartRec", "Hubstaff"),
    ("Time Doctor SmartRec", "TimeDoctor"),
    ("Clockify SmartRec", "Clockify"),
    ("Toggl SmartRec", "Toggl"),
    ("Harvest SmartRec", "Harvest"),
    ("DigitalOcean SmartRec2", "DigitalOcean2"),
    ("Render SmartRec", "Render"),
    ("Netlify SmartRec", "Netlify"),
    ("Vercel SmartRec", "Vercel"),
    ("CircleCI SmartRec", "CircleCI"),
    ("Buildkite SmartRec", "Buildkite"),
    ("Harness SmartRec", "Harness"),
    ("GitHub Actions SmartRec", "GitHubActions"),
    ("Octopus Deploy SmartRec", "OctopusDeploy"),
    ("Codefresh SmartRec", "Codefresh"),
    ("Snyk SmartRec", "Snyk"),
    ("Sonatype SmartRec", "Sonatype"),
    ("Checkmarx SmartRec", "Checkmarx"),
    ("Veracode SmartRec", "Veracode"),
    ("JetBrains SmartRec2", "JetBrains2"),
    ("Scale AI SmartRec", "ScaleAI"),
    ("Labelbox SmartRec", "Labelbox"),
    ("Weights Biases SmartRec", "WnB"),
    ("Weights And Biases SmartRec", "WeightsAndBiases"),
    ("Together AI SmartRec", "TogetherAI"),
    ("Fireworks AI SmartRec", "FireworksAI"),
    ("Groq SmartRec", "Groq"),
    ("Cerebras SmartRec", "Cerebras"),
    ("SambaNova SmartRec", "SambaNova"),
    ("AI21 Labs SmartRec", "AI21Labs"),
    ("Stability AI SmartRec", "StabilityAI"),
    ("Hugging Face SmartRec", "HuggingFace"),
    ("Cohere SmartRec", "Cohere"),
    ("ElevenLabs SmartRec", "ElevenLabs"),
    ("AssemblyAI SmartRec", "AssemblyAI"),
    ("Deepgram SmartRec", "Deepgram"),
    ("Character AI SmartRec", "CharacterAI"),
    ("Perplexity SmartRec", "Perplexity"),
    ("Glean SmartRec", "Glean"),
    ("Notion2 SmartRec", "Notion2"),
    ("OpenAI SmartRec", "OpenAI"),
    ("Anthropic SmartRec", "Anthropic"),
    # ---- INTERNATIONAL REMOTE-FRIENDLY (SMARTRECRUITERS) ----
    ("Visa SmartRec", "Visa"),
    ("Mastercard SmartRec", "Mastercard"),
    ("PayPal SmartRec", "PayPal"),
    ("eBay SmartRec", "eBay"),
    ("Booking.com SmartRec", "BookingCom"),
    ("TripAdvisor SmartRec2", "TripAdvisor2"),
    ("Gartner SmartRec", "Gartner"),
    ("Forrester SmartRec", "Forrester"),
    ("Kantar SmartRec2", "Kantar2"),
    ("IHS Markit SmartRec", "IHSMarkit"),
    ("Moody's SmartRec", "Moodys"),
    ("S&P Global SmartRec", "SPGlobal"),
    ("Bloomberg SmartRec", "Bloomberg"),
    ("Refinitiv SmartRec", "Refinitiv"),
    ("FactSet SmartRec", "FactSet"),
    ("MSCI SmartRec", "MSCI"),
    ("Morningstar SmartRec", "Morningstar"),
    ("Wolters Kluwer SmartRec", "WoltersKluwer"),
    ("RELX SmartRec", "RELX"),
    ("Elsevier SmartRec", "Elsevier"),
    ("Springer Nature SmartRec", "SpringerNature"),
    ("Wise SmartRec", "Wise"),
    ("Revolut SmartRec", "Revolut"),
    ("N26 SmartRec", "N26"),
    ("Monzo SmartRec", "Monzo"),
    ("Starling Bank SmartRec", "StarlingBank"),
    ("OakNorth SmartRec", "OakNorth"),
    ("Checkout SmartRec", "CheckoutCom"),
    ("Adyen SmartRec", "Adyen"),
    ("GoCardless SmartRec", "GoCardless"),
    ("Mollie SmartRec", "Mollie"),
    ("DataRobot SmartRec", "DataRobot"),
    ("H2O.ai SmartRec", "H2OAI"),
    ("Dataiku SmartRec", "Dataiku"),
    ("Appen SmartRec", "Appen"),
    ("Automattic SmartRec", "Automattic"),
    ("Zapier SmartRec2", "Zapier2"),
    ("Buffer SmartRec", "Buffer"),
    ("Elastic SmartRec2", "Elastic2"),
    ("Confluent SmartRec2", "Confluent2"),
    ("HashiCorp SmartRec2", "HashiCorp2"),
    ("Twilio SmartRec", "Twilio"),
    ("DocuSign SmartRec", "DocuSign"),
    ("UiPath SmartRec", "UiPath"),
    ("Automation Anywhere SmartRec", "AutomationAnywhere"),
    # ---- EXPANSION: ADDITIONAL SMARTRECRUITERS ----
    ("Ubisoft SmartRec", "Ubisoft"), ("Electronic Arts SmartRec", "ElectronicArts"),
    ("Square Enix SmartRec", "SquareEnix"), ("Take-Two SmartRec", "TakeTwo"),
    ("Wargaming SmartRec", "Wargaming"), ("Epic Games SmartRec", "EpicGames"),
    ("L Oreal SmartRec", "LOreal"), ("Estee Lauder SmartRec", "EsteeLauder"),
    ("Danone SmartRec", "Danone"), ("Unilever SmartRec", "Unilever"),
    ("Nestle SmartRec", "Nestle"), ("PepsiCo SmartRec", "PepsiCo"),
    ("Coca-Cola SmartRec", "CocaCola"), ("Diageo SmartRec", "Diageo"),
    ("Heineken SmartRec", "Heineken"), ("AB InBev SmartRec", "ABInBev"),
    ("SGS SmartRec", "SGS"), ("Bureau Veritas SmartRec", "BureauVeritas"),
    ("Intertek SmartRec", "Intertek"), ("TUV SUD SmartRec", "TUVSUD"),
    ("TUV Rheinland SmartRec", "TUVRheinland"), ("DNV SmartRec", "DNV"),
    ("Sopra Steria SmartRec", "SopraSteria"), ("Capgemini SmartRec2", "Capgemini2"),
    ("CGI SmartRec2", "CGI2"), ("Atos SmartRec2", "Atos2"),
]

# ============================================================
# BUILD FINAL LIST
# ============================================================
companies = []

seen = set()

def add(name, entry):
    if name not in seen:
        seen.add(name)
        companies.append(entry)

# Greenhouse
for t in greenhouse:
    name, token = t
    add(name, {
        'name': name,
        'ats': 'greenhouse',
        'board_token': token,
        'enabled': True
    })

# Workday
for t in workday:
    name, base_url, tenant, site_name = t
    add(name, {
        'name': name,
        'ats': 'workday',
        'base_url': base_url,
        'tenant': tenant,
        'site_name': site_name,
        'enabled': True
    })

# Lever
for t in lever:
    name, slug = t
    add(name, {
        'name': name,
        'ats': 'lever',
        'company_slug': slug,
        'enabled': True
    })

# Ashby
for t in ashby:
    name, board = t
    add(name, {
        'name': name,
        'ats': 'ashby',
        'board_name': board,
        'enabled': True
    })

# SmartRecruiters
for t in smartrecruiters:
    name, identifier = t
    add(name, {
        'name': name,
        'ats': 'smartrecruiters',
        'company_identifier': identifier,
        'enabled': True
    })

data = {'companies': companies}

with open(r'd:\job_alert_system\companies\companies.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f'Total unique companies written: {len(companies)}')

ats_counts = Counter(c['ats'] for c in companies)
for ats, count in sorted(ats_counts.items()):
    print(f'  {ats:20}: {count}')
